#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-09-27 下午批次文章元数据（六语：zh-Hant 根 / en / ja / ko / fr / es）。

选题说明：任务主题池 30 个选题均已上线，本次为「辅料产品细节 + 采购绩效管理」方向扩展新选题。
已核对 blog/ 全量文件、en|ja|ko|fr|es/blog/ 与 sitemap.xml：
- 「纽扣袋 / 备用扣 / 备品包」关键词在现有正文中无专文覆盖（仅有零星提及）
- 「绩效考核 / KPI / 准交率 / 评分表 / 备援供应商」在现有正文中零覆盖（验厂类文章讲的是准入审核）
"""

ARTICLES = [
    dict(
        slug="garment-spare-button-bag-guide.html",
        body="blog/_body_sparebtn.html",
        title_zh="服装备用纽扣袋与备品包指南：材质、尺寸与配套 | TAGE",
        title_en="Spare Button Bag Guide: Materials, Sizes &amp; Matching | TAGE",
        title_ja="予備ボタン袋ガイド：素材・寸法・同梱の合わせ方 | TAGE",
        title_ko="예비 단추 봉투 가이드: 재질·치수·동봉 정합성 | TAGE",
        title_fr="Sachet de boutons de rechange : matières, formats et assortiment | TAGE",
        title_es="Bolsa de botones de repuesto: materiales, medidas y conjunto | TAGE",
        desc_zh="随成衣附赠的备用纽扣袋怎么做：四种常见形式（自封袋、牛皮纸袋、无纺布袋、纸卡贴窗）的材质与规格、尺寸与内容物反推方法、印刷与童装安全合规要点，以及它与吊牌、织唛、洗水标如何配色配套，附下单前六项确认清单。来自东莞泰阁包装。",
        desc_en="A spare button bag is often the first thing a shopper touches. This guide covers four formats, sizes worked back from contents, printing and child safety.",
        desc_ja="予備ボタン袋の実務ガイド：チャック袋・クラフト袋・不織布ポーチ・台紙貼り窓の4形式、中身から寸法を逆算する方法、印刷と子供服の安全要件、タグ・織りラベル・洗濯表示との配色合わせ、発注前チェック6項目を解説します。",
        desc_ko="예비 단추 봉투 실무 가이드: 지퍼백·크라프트 봉투·부직포 파우치·카드 창봉투 네 가지 형태, 내용물에서 치수를 역산하는 방법, 인쇄와 아동복 안전 요건, 행택·직조 라벨·세탁 표시와의 색상 정합성, 발주 전 확인 6항목을 정리합니다.",
        desc_fr="Sachet de boutons de rechange : quatre formats (refermable, kraft, non tissé, carte à fenêtre), formats déduits du contenu, impression, sécurité enfant et accord avec étiquettes et entretien.",
        desc_es="Bolsa de botones de repuesto: cuatro formatos (resellable, kraft, no tejido, tarjeta con ventana), medidas deducidas del contenido, impresión, seguridad infantil y coordinación con etiquetas.",
        crumb_zh="备用纽扣袋与备品包",
        crumb_en="Spare Button Bags",
        crumb_ja="予備ボタン袋",
        crumb_ko="예비 단추 봉투",
        crumb_fr="Sachets de boutons",
        crumb_es="Bolsas de botones",
        h1_zh="服装辅料备用纽扣袋与备品包指南：材质、尺寸与配套要点",
        h1_en="Spare Button Bags for Garments: Materials, Sizes and How They Fit Your Trims",
        h1_ja="衣料品の予備ボタン袋と備品ポーチ：素材・寸法・副資材との合わせ方",
        h1_ko="의류 예비 단추 봉투와 부속품 파우치: 재질·치수·부자재 정합성",
        h1_fr="Sachets de boutons de rechange : matières, formats et cohérence avec vos accessoires",
        h1_es="Bolsas de botones de repuesto: materiales, medidas y coherencia con tus accesorios",
        tag_zh="辅料配件", tag_en="Accessories", tag_ja="付属品", tag_ko="부속품",
        tag_fr="Accessoires", tag_es="Accesorios",
        sum_zh="备用纽扣袋是消费者拆包后第一个摸到的东西，也是几乎零成本的品牌触点。本文给出自封袋、牛皮纸袋、无纺布袋、纸卡贴窗四种形式的材质与规格对比，讲清如何从内容物反推尺寸、备用线与小样怎么处理、童装打孔与警示语等安全要点，以及它与吊牌、织唛、洗水标的配色与批号如何配套，最后附下单前六项确认清单。",
        sum_en="The spare button bag is one of the first things a shopper touches and almost free brand space. This guide compares four formats, shows how to size the bag from its contents, covers printing and child-safety rules, and explains how it should match your hang tags, woven labels and care labels.",
        sum_ja="予備ボタン袋は開封後に最初に触れるもののひとつで、ほぼ無コストのブランド接点でもあります。4形式の素材と仕様の比較、中身から寸法を逆算する考え方、予備糸や生地見本の扱い、子供服の穴あけと警告文、タグ・織りラベル・洗濯表示との配色とロット番号の揃え方、発注前チェック6項目をまとめます。",
        sum_ko="예비 단추 봉투는 개봉 후 가장 먼저 만지는 것 중 하나이며 거의 무료에 가까운 브랜드 접점입니다. 네 가지 형태의 재질과 사양 비교, 내용물에서 치수를 역산하는 방법, 예비 실과 원단 샘플 처리, 아동복 타공과 경고 문구, 행택·직조 라벨·세탁 표시와의 색상 및 로트 번호 정합성, 발주 전 6가지 확인 항목을 정리합니다.",
        sum_fr="Le sachet de boutons est l'une des premières choses touchées par le client et un support de marque quasi gratuit. Ce guide compare quatre formats, montre comment déduire le format du contenu, traite impression et sécurité enfant, et explique l'accord avec vos étiquettes et tissés.",
        sum_es="La bolsa de botones es una de las primeras cosas que toca el cliente y un soporte de marca casi gratuito. Esta guía compara cuatro formatos, explica cómo deducir las medidas del contenido, cubre impresión y seguridad infantil y detalla la coherencia con colgantes y etiquetas.",
    ),
    dict(
        slug="trim-supplier-scorecard-guide.html",
        body="blog/_body_scorecard.html",
        title_zh="辅料供应商绩效考核指南：准交率、不良率与季度评分表 | TAGE",
        title_en="Trim Supplier Scorecard: On-Time Rate, Defects &amp; Reviews | TAGE",
        title_ja="副資材サプライヤー績効評価：納期遵守率・不良率・四半期スコアカード | TAGE",
        title_ko="부자재 공급업체 성과 평가: 납기 준수율·불량률·분기 스코어카드 | TAGE",
        title_fr="Scorecard fournisseur d'accessoires : ponctualité, défauts et revue trimestrielle | TAGE",
        title_es="Scorecard de proveedores de accesorios: puntualidad, defectos y revisión trimestral | TAGE",
        desc_zh="辅料供应商绩效考核怎么做：准交率、品质不良率、异常响应、变更打样配合与文件合规五个指标的统计口径与参考区间，季度评分表的权重设计与 A/B/C/D 分档，订单分配、改进计划与备援供应商的落地用法，附三个常见误区。来自东莞泰阁包装。",
        desc_en="How to score trim suppliers: on-time rate, defect rate, response speed and documents, plus weights, tiers and how scores drive order allocation and backups.",
        desc_ja="副資材サプライヤーの績効評価ガイド：納期遵守率・品質不良率・異常対応・変更対応・書類の5指標の集計定義と参考レンジ、四半期スコアカードの重みとA/B/C/D区分、発注配分・改善計画・代替先の使い方、よくある3つの誤りを整理します。",
        desc_ko="부자재 공급업체 성과 평가 가이드: 납기 준수율·품질 불량률·이상 대응·변경 대응·문서 등 다섯 지표의 집계 기준과 참고 구간, 분기 스코어카드 가중치와 A/B/C/D 등급, 발주 배분·개선 계획·대체 공급 활용법, 흔한 실수 세 가지를 정리합니다.",
        desc_fr="Évaluer un fournisseur d'accessoires : ponctualité, taux de défauts, réactivité, révisions et documents, avec pondérations, niveaux A à D et usage réel des notes.",
        desc_es="Evaluar proveedores de accesorios: puntualidad, tasa de defectos, respuesta, cambios y documentos, con pesos, niveles A a D y uso real de las notas.",
        crumb_zh="供应商绩效考核",
        crumb_en="Supplier Scorecard",
        crumb_ja="サプライヤー績効評価",
        crumb_ko="공급업체 성과 평가",
        crumb_fr="Scorecard fournisseur",
        crumb_es="Scorecard de proveedores",
        h1_zh="服装辅料供应商绩效考核指南：准交率、不良率与季度评分表怎么定",
        h1_en="Trim Supplier Performance Scorecard: On-Time Rate, Defects and Quarterly Reviews",
        h1_ja="副資材サプライヤーの績効評価：納期遵守率・不良率と四半期スコアカードの作り方",
        h1_ko="부자재 공급업체 성과 평가: 납기 준수율·불량률과 분기 스코어카드 설계",
        h1_fr="Scorecard de performance fournisseur : ponctualité, défauts et revue trimestrielle",
        h1_es="Scorecard de desempeño de proveedores: puntualidad, defectos y revisión trimestral",
        tag_zh="采购管理", tag_en="Supply Management", tag_ja="調達管理", tag_ko="구매 관리",
        tag_fr="Gestion des achats", tag_es="Gestión de compras",
        sum_zh="验厂回答「有没有能力」，绩效考核回答「每个月是否真的做到」。本文给出准交率、品质不良率、异常响应速度、变更与打样配合、文件与合规完整度五个指标的统计口径与参考区间，说明数据该挂在采购台账、收货记录与异常单上，并附季度评分表的权重示例、A/B/C/D 分档对应的订单分配规则、改进计划的写法与三个常见误区。",
        sum_en="An audit tells you whether a supplier is capable; a scorecard tells you whether it delivered. This article sets out five metrics with definitions and reference ranges, shows which existing records to hang them on, and gives a quarterly weighting, A to D tiers, allocation rules and the three mistakes to avoid.",
        sum_ja="監査は「能力があるか」に、スコアカードは「毎月実行できているか」に答えます。納期遵守率・品質不良率・異常対応・変更とサンプル対応・書類の5指標について集計定義と参考レンジを示し、発注台帳・入荷記録・異常票に紐づける運用、四半期の重み例、A/B/C/D区分に応じた配分ルール、改善計画の書き方、よくある3つの誤りをまとめます。",
        sum_ko="심사는 '능력이 있는가'에, 스코어카드는 '매달 실제로 해냈는가'에 답합니다. 납기 준수율·품질 불량률·이상 대응·변경과 샘플 대응·문서 다섯 지표의 집계 정의와 참고 구간을 제시하고, 발주 대장·입고 기록·이상 티켓에 연결하는 운영, 분기 가중치 예시, A/B/C/D 등급별 배분 규칙, 개선 계획 작성법, 흔한 실수 세 가지를 정리합니다.",
        sum_fr="L'audit dit si le fournisseur est capable ; la scorecard dit s'il a livré. Cet article pose cinq indicateurs avec définitions et plages de référence, indique sur quels registres existants les adosser, et fournit une pondération trimestrielle, des niveaux A à D, des règles d'attribution et les trois erreurs à éviter.",
        sum_es="La auditoría dice si el proveedor es capaz; la scorecard si realmente cumplió. Este artículo plantea cinco indicadores con definiciones y rangos, indica sobre qué registros existentes apoyarlos y ofrece pesos trimestrales, niveles A a D, reglas de reparto y los tres errores a evitar.",
    ),
]
