#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-09-27 上午批次文章元数据（六语：zh-Hant 根 / en / ja / ko / fr / es）。

选题说明：任务主题池 30 个选题均已上线，本次为「采购商务运营」方向扩展新选题，
已核对 blog/ 全量文件与 sitemap.xml 无重复（grep 确认「合同条款 / 变更管理 / 索赔 / 不可抗力」等关键词在现有正文中无专文覆盖）。
"""

ARTICLES = [
    dict(
        slug="trim-order-contract-terms-guide.html",
        body="blog/_body_contract.html",
        title_zh="服装辅料订单合同条款指南：交期、质量判定与索赔期限 | TAGE",
        title_en="Trim Order Contract Terms: Delivery, Quality Claims &amp; Deadlines | TAGE",
        title_ja="副資材発注の契約条件ガイド：納期・品質判定・クレーム期限 | TAGE",
        title_ko="부자재 주문 계약 조건 가이드: 납기·품질 판정·클레임 기한 | TAGE",
        title_fr="Conditions contractuelles d'une commande d'accessoires : délais, qualité, réclamations | TAGE",
        title_es="Condiciones contractuales en pedidos de accesorios: plazos, calidad y reclamaciones | TAGE",
        desc_zh="辅料订单金额不大却最容易扯皮：交期写发货日还是到货日、验收以确认样还是规格书为准、到货后多久内提异议、原材料涨价算不算不可抗力、终止后版费与余料怎么处理。本文逐条拆解一份辅料订单确认书该写清的条款，附下单前六项确认清单。来自东莞泰阁包装。",
        desc_en="Trim order contract terms: shipping versus arrival dates, acceptance standards, claim windows, force majeure wording and how tooling and leftovers are handled.",
        desc_ja="副資材発注の契約条件ガイド：納期は出荷日か到着日か、検収基準は確認見本か仕様書か、外観クレームの期限、原材料高騰と不可抗力の切り分け、終了時の版代・余剰在庫の扱いを整理します。",
        desc_ko="부자재 주문 계약 조건 가이드: 납기를 출하일로 볼지 도착일로 볼지, 검수 기준은 확인 샘플인지 사양서인지, 외관 클레임 기한, 원자재 인상과 불가항력의 구분, 종료 시 판 비용과 잔여 재고 처리까지 정리합니다.",
        desc_fr="Conditions contractuelles d'une commande d'accessoires : date d'expédition ou de livraison, base d'acceptation, délais de réclamation, force majeure et sort des outillages et reliquats.",
        desc_es="Condiciones contractuales en pedidos de accesorios: fecha de envío o de entrega, base de aceptación, plazos de reclamación, fuerza mayor y destino de utillajes y sobrantes.",
        crumb_zh="订单合同条款",
        crumb_en="Contract Terms",
        crumb_ja="契約条件",
        crumb_ko="계약 조건",
        crumb_fr="Conditions contractuelles",
        crumb_es="Condiciones contractuales",
        h1_zh="服装辅料订单合同条款指南：交期、质量判定与索赔期限怎么写",
        h1_en="Trim Order Contract Terms: Delivery, Quality Judgement and Claim Deadlines",
        h1_ja="副資材発注の契約条件：納期・品質判定・クレーム期限の書き方",
        h1_ko="부자재 주문 계약 조건: 납기·품질 판정·클레임 기한 작성법",
        h1_fr="Conditions contractuelles des commandes d'accessoires : délais, qualité, réclamations",
        h1_es="Condiciones contractuales del pedido de accesorios: plazos, calidad y reclamaciones",
        tag_zh="采购合同", tag_en="Contracts", tag_ja="契約", tag_ko="계약",
        tag_fr="Contrats", tag_es="Contratos",
        sum_zh="辅料单价低、单笔金额小，多数纠纷不是质量问题，而是下单时没说清。本文把一份辅料订单确认书该锁定的六件事（规格与确认样、数量与溢短装、交期口径、验收标准、异常处理、终止与余料）逐条拆开，给出交期「发货日 vs 到货日」的取舍、三层判定标准、异议期限与不可抗力的口径，并附下单前六项确认清单。",
        sum_en="Trim orders are small in value but easy to argue about. This guide breaks down the six clauses worth locking in — spec and approval sample, quantity tolerance, delivery date wording, acceptance standard, exception handling, termination and leftovers — plus claim deadlines and force majeure wording.",
        sum_ja="副資材は単価も金額も小さいのに、揉めやすい。仕様と確認見本、数量と過不足許容、納期の書き方、検収基準、異常時の連絡、終了時の余剰在庫という6項目に加え、クレーム期限と不可抗力の切り分けまで整理します。",
        sum_ko="부자재는 금액이 작지만 분쟁이 잦습니다. 사양과 확인 샘플, 수량 과부족 허용, 납기 문구, 검수 기준, 이상 발생 시 대응, 종료 시 잔여 재고 등 여섯 항목과 클레임 기한, 불가항력 구분을 정리합니다.",
        sum_fr="Les commandes d'accessoires sont de faible montant mais sources de litiges. Ce guide détaille les six clauses à verrouiller — spécification et échantillon, tolérance de quantité, formulation du délai, base d'acceptation, exceptions, fin de commande — et les délais de réclamation.",
        sum_es="Los pedidos de accesorios son de importe bajo pero generan disputas. Esta guía detalla las seis cláusulas a fijar —especificación y muestra, tolerancia de cantidad, redacción del plazo, base de aceptación, incidencias y cierre— además de plazos de reclamación.",
    ),
    dict(
        slug="trim-order-change-cancellation-guide.html",
        body="blog/_body_change.html",
        title_zh="辅料订单变更与取消指南：改稿、加减量与生效断点 | TAGE",
        title_en="Changing or Cancelling a Trim Order: Revisions, Quantities &amp; Cut-Offs | TAGE",
        title_ja="副資材発注の変更・キャンセルガイド：図案変更・数量増減・切替点 | TAGE",
        title_ko="부자재 주문 변경·취소 가이드: 도안 변경·수량 증감·적용 분기점 | TAGE",
        title_fr="Modifier ou annuler une commande d'accessoires : visuels, quantités, points de bascule | TAGE",
        title_es="Modificar o cancelar un pedido de accesorios: artes, cantidades y puntos de corte | TAGE",
        desc_zh="辅料订单已经下了要改，是最容易变成「临时加钱」的环节。本文讲清变更成本的五个台阶、改文字与改尺寸分别要动什么、加减量的结算口径、变更单与版本号怎么管住新旧混装，以及取消按已发生成本结算的原则。来自东莞泰阁包装。",
        desc_en="Trim order changes: five cost stages from not scheduled to finished, what changing copy or size moves, quantity changes, cut-off points and cancellation.",
        desc_ja="副資材発注の変更ガイド：未手配・資材手配済・版作成済・生産中・完成の5段階ごとの変更コスト、文字変更と寸法変更で動くもの、数量増減の精算、変更票と版番号による新旧混在の防止、キャンセル時の実費精算を解説します。",
        desc_ko="부자재 주문 변경 가이드: 미배치·자재 준비·판 제작·생산 중·완성 5단계별 변경 비용, 문구 변경과 치수 변경의 차이, 수량 증감 정산, 변경서와 버전 관리로 신구 혼입 방지, 취소 시 실비 정산 원칙을 정리합니다.",
        desc_fr="Modifier une commande d'accessoires : les cinq paliers de coût (non lancé, matières commandées, outillage réalisé, en production, terminé), effets d'un changement de texte ou de cote, quantités et annulation au coût réel.",
        desc_es="Modificar un pedido de accesorios: los cinco escalones de coste (sin programar, material pedido, utillaje hecho, en producción, terminado), efecto de cambiar texto o medidas, cantidades y cancelación al coste real.",
        crumb_zh="订单变更管理",
        crumb_en="Order Changes",
        crumb_ja="発注変更",
        crumb_ko="주문 변경",
        crumb_fr="Modifications de commande",
        crumb_es="Cambios de pedido",
        h1_zh="辅料订单变更与取消指南：改稿、加减量与生效断点怎么管",
        h1_en="Changing or Cancelling a Trim Order: Revisions, Quantity Changes and Cut-Offs",
        h1_ja="副資材発注の変更とキャンセル：図案変更・数量増減・切替点の管理",
        h1_ko="부자재 주문 변경과 취소: 도안 변경·수량 증감·적용 분기점 관리",
        h1_fr="Modifier ou annuler une commande d'accessoires : visuels, quantités et points de bascule",
        h1_es="Modificar o cancelar un pedido de accesorios: artes, cantidades y puntos de corte",
        tag_zh="订单管理", tag_en="Order Management", tag_ja="受発注管理", tag_ko="주문 관리",
        tag_fr="Gestion des commandes", tag_es="Gestión de pedidos",
        sum_zh="已经下单的辅料要改稿、加量或取消，成本取决于「改在哪个阶段」。本文把变更分成五个成本台阶，讲清改文字、改颜色、改尺寸、改条码分别要动哪些版与流程，加减量按已采购物料还是按成品结算，如何用变更单与版本号管住新旧混装，以及取消与暂停按已发生成本结算的原则，附一封变更邮件该写的六件事。",
        sum_en="Revising, adding to or cancelling a trim order costs what the stage costs. This guide sets out five cost stages, what copy, colour, size and barcode changes actually move, how up and down quantities settle, how a change note and version numbers stop old and new stock mixing, and the settle-at-cost rule for cancellations.",
        sum_ja="発注済みの副資材を変更・追加・取消する場合、コストは「どの段階で変えるか」で決まります。5つのコスト段階、文字・色・寸法・バーコード変更で動く版と工程、数量増減の精算基準、変更票と版番号による新旧混在の防止、キャンセル時の実費精算、変更メールに書く6項目を整理します。",
        sum_ko="이미 발주한 부자재의 도안 변경·증량·취소 비용은 '어느 단계에서 바꾸는가'에 달려 있습니다. 다섯 단계 비용, 문구·색상·치수·바코드 변경 시 움직이는 판과 공정, 수량 증감 정산 기준, 변경서와 버전 번호로 신구 혼입 방지, 취소 시 실비 정산 원칙, 변경 메일에 담을 여섯 항목을 정리합니다.",
        sum_fr="Modifier, augmenter ou annuler une commande coûte selon l'étape atteinte. Ce guide présente cinq paliers de coût, ce que déplacent les changements de texte, couleur, cote et code-barres, le règlement des quantités, la gestion des versions pour éviter le mélange, et l'annulation au coût réel.",
        sum_es="Modificar, ampliar o cancelar un pedido cuesta según la etapa alcanzada. Esta guía presenta cinco escalones de coste, qué mueve cambiar texto, color, medida o código de barras, la liquidación de cantidades, la gestión de versiones para evitar mezclas y la cancelación al coste real.",
    ),
]
