#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-09-28 上午批次文章元数据（六语：zh-Hant 根 / en / ja / ko / fr / es）。

选题说明：任务主题池 30 个选题均已上线，本次为「欧盟合规文件链」方向扩展新选题。
已核对 blog/ 全量文件、en|ja|ko|fr|es/blog/ 与 sitemap.xml：
- 「EUDR / 零毁林 / 毁林」在现有 200+ 篇文章中零覆盖（本次第 1 篇为全新主题）
- 「Triman / LUCID / VerpackG / EPR」仅在少数正文中被顺带提及，无专文；现有包装合规文章讲的是 PPWR 与可回收设计，未讲各国注册体系与标识印制分工（本次第 2 篇为全新主题）
"""

ARTICLES = [
    dict(
        slug="eu-deforestation-regulation-packaging.html",
        body="blog/_body_eudr.html",
        title_zh="欧盟零毁林法规 EUDR 与纸制辅料包装：文件链怎么准备 | TAGE",
        title_en="EUDR and Paper Trims &amp; Packaging: Building the Document Chain | TAGE",
        title_ja="EU 森林破壊防止規則（EUDR）と紙系副資材・包装：書類チェーンの整え方 | TAGE",
        title_ko="EU 산림전용 방지 규정(EUDR)과 종이 부자재·포장: 서류 체계 준비 | TAGE",
        title_fr="Règlement EUDR et accessoires papier : bâtir la chaîne documentaire | TAGE",
        title_es="Reglamento EUDR y accesorios de papel: preparar la cadena documental | TAGE",
        desc_zh="欧盟零毁林法规（EUDR）把纸袋、牛皮纸吊牌、纸盒等纸制辅料与包装纳入溯源范围。本文讲清品牌、进口商与供应商的分工、四类纸源文件怎么搭、报价阶段常见误区，以及下单前该问供应方的六个问题。来自东莞泰阁包装。",
        desc_en="How the EU Deforestation Regulation affects paper bags, kraft hang tags and boxes: who files the DDS, which documents prove origin, and the pitfalls to avoid.",
        desc_ja="EU 森林破壊防止規則（EUDR）と紙系副資材・包装の実務ガイド：紙袋・クラフト紙タグ・紙箱が対象となる理由、ブランド・輸入者・サプライヤーの分担、FSC の CoC 認証・製紙会社声明・ロット対応・地理座標という 4 種類の書類の整え方、見積り段階の 4 つの誤解、発注前の 6 項目を解説します。",
        desc_ko="EU 산림전용 방지 규정(EUDR)과 종이 부자재·포장 실무: 종이백, 크라프트 행택, 종이 상자가 대상이 되는 이유, 브랜드·수입자·공급업체의 역할 분담, FSC CoC 인증·제지사 선언·로트 대응·지리 좌표 네 가지 서류 준비법, 견적 단계의 네 가지 오해, 발주 전 여섯 가지 질문을 정리합니다.",
        desc_fr="EUDR et accessoires papier : qui dépose la DDS, quels documents prouvent l'origine (certificat CoC FSC, déclaration du papetier, lots, géolocalisation) et les pièges à éviter au devis.",
        desc_es="EUDR y accesorios de papel: quién presenta la DDS, qué documentos prueban el origen (CoC FSC, declaración del papetier, lotes, geolocalización) y los errores a evitar al cotizar.",
        crumb_zh="EUDR 与纸制辅料",
        crumb_en="EUDR &amp; Paper Trims",
        crumb_ja="EUDR と紙系副資材",
        crumb_ko="EUDR과 종이 부자재",
        crumb_fr="EUDR et accessoires papier",
        crumb_es="EUDR y accesorios de papel",
        h1_zh="欧盟零毁林法规（EUDR）与纸制辅料、包装：文件链该怎么准备",
        h1_en="EUDR and Paper-Based Trims &amp; Packaging: How to Build the Document Chain",
        h1_ja="EU 森林破壊防止規則（EUDR）と紙系副資材・包装：書類チェーンの組み立て方",
        h1_ko="EU 산림전용 방지 규정(EUDR)과 종이 부자재·포장: 서류 체계 구축 방법",
        h1_fr="EUDR et accessoires, emballages papier : construire la chaîne documentaire",
        h1_es="EUDR y accesorios y envases de papel: cómo construir la cadena documental",
        tag_zh="合规法规", tag_en="Compliance", tag_ja="コンプライアンス", tag_ko="컴플라이언스",
        tag_fr="Conformité", tag_es="Cumplimiento",
        sum_zh="欧盟买家现在问的不只是「有没有 FSC 证书」，而是「你们的纸袋、牛皮纸吊牌用的是哪里来的浆、能不能出文件」。本文讲清 EUDR 的三个基本事实：它管的是来源而不是观感、判断适用看 HS 编码而不是行业、提交申报的义务落在品牌与进口商身上。随后给出纸制辅料的四类文件（FSC/PEFC 产销监管链证书、纸厂声明、订单与批号对应、地理坐标信息）分别由谁出具、缺了会怎样，梳理报价阶段最常见的四个误区，并附下单前该问供应方的六个问题。",
        sum_en="European buyers no longer ask only for an FSC certificate; they ask where the pulp in your paper bags and kraft tags comes from, and whether you can document it. This article sets out three basics about EUDR — it targets origin rather than appearance, applicability follows the HS code rather than the industry, and the filing duty sits with the brand or importer. It then shows who issues each of the four document types (FSC or PEFC chain-of-custody certificate, mill declaration, order-to-lot record, geolocation data), what breaks when one is missing, the four misunderstandings heard most at quotation stage, and six questions to put to a supplier before ordering.",
        sum_ja="欧州のバイヤーは今、FSC 認証の有無だけでなく「紙袋やクラフト紙タグのパルプはどこ産で、書類を出せるか」を尋ねます。本記事では EUDR の基本を 3 点（見るのは由来であり見た目ではない、適用判断は業種ではなく HS コード、提出義務はブランド・輸入者にある）に整理し、紙系副資材の 4 種類の書類（FSC・PEFC の CoC 認証、製紙会社声明、注文とロットの対応記録、地理座標情報）について誰が発行し、欠けると何が起きるかを示します。さらに見積り段階でよくある 4 つの誤解と、発注前に確認すべき 6 項目をまとめます。",
        sum_ko="유럽 바이어들은 이제 FSC 인증 유무만 묻지 않고 '종이백과 크라프트 행택의 펄프가 어디서 오며 서류로 증명할 수 있는가'를 확인합니다. 이 글은 EUDR의 기본 세 가지(외관이 아니라 출처를 규제, 적용 판단은 업종이 아니라 HS 코드, 제출 의무는 브랜드·수입자에게 있음)를 정리하고, 종이 부자재의 네 가지 서류(FSC·PEFC CoC 인증서, 제지사 선언서, 주문-로트 대응 기록, 지리 좌표 정보)를 누가 발급하고 빠지면 어떤 문제가 생기는지 설명합니다. 이어서 견적 단계에서 흔한 네 가지 오해와 발주 전 확인할 여섯 가지 질문을 제시합니다.",
        sum_fr="Les acheteurs européens ne demandent plus seulement un certificat FSC : ils veulent savoir d'où vient la pâte de vos sacs et étiquettes kraft, et si vous pouvez le prouver. Cet article pose trois fondamentaux de l'EUDR — l'origine plutôt que l'apparence, le code SH plutôt que le secteur, une obligation de dépôt portée par la marque ou l'importateur — puis détaille qui émet chacun des quatre documents (certificat CoC FSC ou PEFC, déclaration du papetier, registre commande/lot, géolocalisation), ce qui casse quand il en manque un, les quatre malentendus du devis et six questions à poser avant commande.",
        sum_es="Los compradores europeos ya no piden solo un certificado FSC: preguntan de dónde viene la pasta de sus bolsas y colgantes kraft y si puede documentarse. Este artículo fija tres bases del EUDR —el origen antes que la apariencia, el código HS antes que el sector, y una obligación de presentación que recae en la marca o el importador— y detalla quién emite cada uno de los cuatro documentos (certificado CoC FSC o PEFC, declaración de fábrica, registro pedido/lote, geolocalización), qué se rompe si falta uno, los cuatro malentendidos del presupuesto y seis preguntas antes de pedir.",
    ),
    dict(
        slug="eu-packaging-epr-triman-guide.html",
        body="blog/_body_epr.html",
        title_zh="欧盟包装 EPR 与回收标识指南：Triman、LUCID 怎么印 | TAGE",
        title_en="EU Packaging EPR &amp; Sorting Labels: Triman, LUCID &amp; Printing | TAGE",
        title_ja="EU 包装 EPR と分別表示ガイド：Triman・LUCID の印字実務 | TAGE",
        title_ko="EU 포장 EPR과 분리배출 표시: Triman·LUCID 인쇄 실무 | TAGE",
        title_fr="EPR emballage UE et logos de tri : Triman, LUCID et impression | TAGE",
        title_es="EPR de envases UE y logos de reciclaje: Triman, LUCID e impresión | TAGE",
        desc_zh="欧盟包装 EPR 到底要求什么：谁负责注册缴费、Triman 与 LUCID 等标识由谁提供文件、吊牌算不算包装，以及标识的颜色、尺寸、位置与改版管理要点，另附包装下线前七项确认清单。来自东莞泰阁包装。",
        desc_en="EU packaging EPR for garment brands: who registers, who supplies the Triman or LUCID artwork, whether hang tags count as packaging, and where the logo prints.",
        desc_ja="EU 包装 EPR と分別表示の実務ガイド：登録・負担の主体、Triman や LUCID のファイル提供者、タグが包装に当たるかの考え方、袋・箱への印字位置と色・サイズ・版管理、印字前の確認 7 項目を整理します。",
        desc_ko="EU 포장 EPR과 분리배출 표시 실무: 등록·부담 주체, Triman·LUCID 파일 제공자, 행택이 포장에 해당하는지에 대한 판단, 봉투·상자 인쇄 위치와 색상·크기·버전 관리, 인쇄 전 확인 일곱 가지를 정리합니다.",
        desc_fr="EPR emballage UE : qui s'enregistre, qui fournit le fichier Triman ou LUCID, l'étiquette compte-t-elle comme emballage, où l'imprimer et comment gérer les versions.",
        desc_es="EPR de envases en la UE: quién se registra, quién aporta el archivo Triman o LUCID, si el colgante cuenta como envase y dónde imprimir el logo.",
        crumb_zh="包装 EPR 与回收标识",
        crumb_en="Packaging EPR &amp; Labels",
        crumb_ja="包装 EPR と分別表示",
        crumb_ko="포장 EPR·분리배출 표시",
        crumb_fr="EPR emballage et logos",
        crumb_es="EPR de envases y logos",
        h1_zh="欧盟包装 EPR 与回收标识指南：Triman、LUCID 该印在哪里、由谁提供",
        h1_en="EU Packaging EPR and Sorting Labels: What to Print, Where, and Who Supplies It",
        h1_ja="EU 包装 EPR と分別表示：何をどこに印字し、誰がファイルを用意するか",
        h1_ko="EU 포장 EPR과 분리배출 표시: 무엇을 어디에 인쇄하고 누가 파일을 제공하는가",
        h1_fr="EPR emballage UE et logos de tri : quoi imprimer, où, et qui fournit le fichier",
        h1_es="EPR de envases en la UE y logos de clasificación: qué imprimir, dónde y quién lo aporta",
        tag_zh="合规法规", tag_en="Compliance", tag_ja="コンプライアンス", tag_ko="컴플라이언스",
        tag_fr="Conformité", tag_es="Cumplimiento",
        sum_zh="欧盟客户开始问「包装上要不要印回收标识」。这不是排版问题，而是包装 EPR：谁把包装投放某国市场，谁就在该国注册、申报并缴费，而 Triman、分拣说明这类标识是这套义务露在货架上的那一角。本文用一张表理清法国、德国、西班牙、意大利的注册体系与标识差异，说明义务人通常是品牌、进口商或跨境卖家而不是制袋厂，讨论「吊牌算不算包装」这个最容易扯不清的问题，并给出标识的颜色尺寸、印面位置、印刷方式与版本管理五个工艺要点，最后附包装下线前的七项确认清单。",
        sum_en="European buyers have started asking whether their packaging needs a recycling logo. That is not a layout question but packaging EPR: whoever places packaging on a country's market registers, reports and pays there, and logos such as Triman are the visible corner of that duty. This article uses one table to compare the registries and marking rules of France, Germany, Spain and Italy, explains that the obligated party is usually the brand, importer or cross-border seller rather than the bag maker, works through the perennial question of whether a hang tag counts as packaging, and gives five production points — colour and size, print position, printing method and version control — plus a seven-item checklist before the packaging goes to print.",
        sum_ja="欧州のバイヤーは「包装にリサイクル表示が必要か」を尋ね始めました。これはレイアウトではなく包装 EPR の話です。包装をある国の市場に置く事業者がその国で登録・報告・負担を行い、Triman などの表示はその義務が店頭で見える部分です。本記事はフランス・ドイツ・スペイン・イタリアの登録制度と表示の違いを 1 つの表にまとめ、義務主体が通常はブランド・輸入者・越境販売者であり製袋工場ではないことを説明し、「タグは包装に当たるか」という最も揉めやすい論点を整理します。さらに色とサイズ、印字位置、印刷方式、版管理という 5 つの実務ポイントと、印刷前の確認 7 項目を示します。",
        sum_ko="유럽 바이어들은 '포장에 재활용 표시가 필요한가'를 묻기 시작했습니다. 이는 레이아웃 문제가 아니라 포장 EPR의 문제입니다. 특정 국가 시장에 포장을 출시하는 사업자가 그 국가에서 등록·신고·부담하며, Triman 같은 표시는 그 의무가 매대에서 드러나는 부분입니다. 이 글은 프랑스·독일·스페인·이탈리아의 등록 제도와 표시 차이를 한 표로 정리하고, 의무 주체가 보통 브랜드·수입자·크로스보더 판매자이며 봉투 제조사가 아님을 설명합니다. 가장 자주 다투는 '행택이 포장인가' 문제를 다루고, 색상·크기, 인쇄 위치, 인쇄 방식, 버전 관리라는 다섯 가지 실무 포인트와 인쇄 전 확인 일곱 가지를 제시합니다.",
        sum_fr="Les acheteurs européens demandent si leur emballage doit porter un logo de tri. Ce n'est pas une question de maquette mais d'EPR emballage : celui qui met l'emballage sur le marché d'un pays s'y enregistre, déclare et paie, et des logos comme le Triman en sont la partie visible. Un tableau compare les registres et règles de la France, de l'Allemagne, de l'Espagne et de l'Italie ; l'article rappelle que le redevable est en général la marque, l'importateur ou le vendeur transfrontalier, traite la question récurrente de l'étiquette suspendue, puis détaille cinq points de production — couleur et taille, position, procédé, gestion des versions — et une liste de sept vérifications avant impression.",
        sum_es="Los compradores europeos preguntan si su envase necesita un logo de reciclaje. No es una cuestión de maquetación sino de EPR de envases: quien pone el envase en el mercado de un país se registra, declara y paga allí, y logos como el Triman son la parte visible de esa obligación. Una tabla compara los registros y reglas de Francia, Alemania, España e Italia; el artículo recuerda que el obligado suele ser la marca, el importador o el vendedor transfronterizo, aborda la pregunta recurrente de si el colgante cuenta como envase y detalla cinco puntos de producción —color y tamaño, posición, método de impresión, gestión de versiones— con una lista de siete comprobaciones antes de imprimir.",
    ),
]
