#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-10-05 晚间批次（20:00）每日更新：2 篇新文章元数据
- REACH SVHC 与服装辅料合规指南（reach-svhc-apparel-trims-guide）
- 服装标签的盲文与触觉标识指南（braille-tactile-label-guide）
"""

ARTICLES = [
    dict(
        slug="reach-svhc-apparel-trims-guide.html",
        body="blog/_body_svhc.html",
        title_zh="REACH SVHC 与服装辅料合规指南：0.1% 阈值、告知义务与 SCIP 申报 | TAGE",
        title_en="REACH SVHC for Apparel Trims: 0.1% Threshold, Article 33 and SCIP | TAGE",
        title_ja="衣料副資材の REACH SVHC 対応ガイド：0.1% 閾値・通知義務・SCIP 届出 | TAGE",
        title_ko="의류 부자재 REACH SVHC 가이드: 0.1% 기준·고지 의무·SCIP 신고 | TAGE",
        title_fr="REACH SVHC et accessoires textiles : seuil 0,1 %, article 33 et SCIP | TAGE",
        title_es="REACH SVHC en accesorios textiles: umbral del 0,1 %, artículo 33 y SCIP | TAGE",
        desc_zh="服装辅料出口欧盟要过的不只是禁限用清单：SVHC 含量超过 0.1% 就有告知义务，2021 年起还要做 SCIP 申报。本文讲清阈值怎么算、金属件与软 PVC 的风险点、替代选材与要备齐的合规文件，来自东莞泰阁包装。",
        desc_en="REACH SVHC for apparel trims: how the 0.1% threshold is calculated, Article 33 duties, SCIP filing, high-risk materials and the documents EU buyers request.",
        desc_ja="衣料副資材の REACH SVHC 対応ガイド。0.1% 閾値の計算方法、Article 33 の情報伝達義務、SCIP への届出、金属部品や軟質 PVC の高リスク物質、低リスクへの置換、EU バイヤーが求める書類を整理。東莞泰閣包装。",
        desc_ko="의류 부자재 REACH SVHC 가이드. 0.1% 기준 계산법, Article 33 정보 전달 의무, SCIP 신고, 금속 부품과 연질 PVC의 고위험 물질, 저위험 대체, EU 바이어가 요구하는 서류를 정리했습니다. 둥관 TAGE 패키징.",
        desc_fr="REACH SVHC pour les accessoires textiles : calcul du seuil de 0,1 %, obligations de l'article 33, dépôt SCIP, substances à risque et documents demandés par les acheteurs européens.",
        desc_es="REACH SVHC en accesorios textiles: cálculo del umbral del 0,1 %, obligaciones del artículo 33, presentación SCIP, sustancias de riesgo y documentos que piden los compradores europeos.",
        crumb_zh="REACH SVHC 合规",
        crumb_en="REACH SVHC",
        crumb_ja="REACH SVHC 対応",
        crumb_ko="REACH SVHC 대응",
        crumb_fr="REACH SVHC",
        crumb_es="REACH SVHC",
        h1_zh="REACH SVHC 与服装辅料合规指南：0.1% 阈值、告知义务与 SCIP 申报",
        h1_en="REACH SVHC for Apparel Trims: 0.1% Threshold, Article 33 and SCIP",
        h1_ja="衣料副資材の REACH SVHC 対応ガイド：0.1% 閾値・通知義務・SCIP 届出",
        h1_ko="의류 부자재 REACH SVHC 가이드: 0.1% 기준·고지 의무·SCIP 신고",
        h1_fr="REACH SVHC et accessoires textiles : seuil de 0,1 %, article 33 et SCIP",
        h1_es="REACH SVHC en accesorios textiles: umbral del 0,1 %, artículo 33 y SCIP",
        tag_zh="合规指南",
        tag_en="Compliance",
        tag_ja="コンプライアンス",
        tag_ko="컴플라이언스",
        tag_fr="Conformité",
        tag_es="Cumplimiento",
        sum_zh="欧盟买家问「辅料是否含 SVHC」，要的从来不只是检测报告，而是一条证据链：含量有没有超过 0.1%（w/w）、超过时告知义务有没有履行、SCIP 申报做了没有。本文把 REACH 对辅料的四条硬约束讲清楚，列出金属件、软 PVC、深色橡胶、染色织物与含氟涂层最常被查出的物质与法规出处，说明 0.1% 要按「物品」而不是整件衣服计算，梳理 SCIP 的申报主体与内容、供应商应备齐的六类文件、从选材端替换降险的做法，并给出把 REACH 写进询价单的清单。",
        sum_en="When an EU buyer asks whether trims contain SVHC, the answer is not a test report but an evidence chain: is anything above 0.1% (w/w), was the duty to inform met, was SCIP filed. This guide sets out the four hard REACH obligations for trims, the substances most often found in metal parts, soft PVC, dark rubber, dyed textiles and fluorinated coatings with their legal sources, why the 0.1% is assessed per article rather than per garment, who files SCIP and what it contains, the six documents a supplier should hold, and how to write REACH requirements into a quotation request.",
        sum_ja="EU のバイヤーが「副資材に SVHC は含まれますか」と尋ねるとき、求めているのは試験報告書ではなく証拠の連鎖です。0.1%（w/w）を超える含有があるか、情報伝達義務を果たしたか、SCIP へ届け出たか。本記事は REACH が副資材に課す4つの義務、金属部品・軟質 PVC・黒色ゴム・染色生地・フッ素コーティングで最も検出されやすい物質と規制根拠、0.1% が衣服全体ではなく「物品」単位で計算される理由、SCIP の届出主体と記載内容、供給者が備えるべき6種類の書類、選材段階での置換によるリスク低減、そして見積依頼に REACH 要件を書き込むためのチェックリストをまとめます。",
        sum_ko="EU 바이어가 부자재에 SVHC가 있는지 물을 때 원하는 것은 시험 성적서가 아니라 증거 체인입니다. 0.1%(w/w) 초과 여부, 정보 전달 의무 이행 여부, SCIP 신고 여부입니다. 이 글은 REACH가 부자재에 부과하는 네 가지 의무, 금속 부품·연질 PVC·검정 고무·염색 원단·불소 코팅에서 가장 자주 검출되는 물질과 법규 근거, 0.1%가 완성 의류가 아니라 '물품' 단위로 계산되는 이유, SCIP 신고 주체와 내용, 공급자가 갖춰야 할 여섯 가지 서류, 소재 대체를 통한 위험 저감, 견적 요청서에 REACH 요건을 기재하는 체크리스트를 정리합니다.",
        sum_fr="Quand un acheteur européen demande si les accessoires contiennent des SVHC, la réponse n'est pas un rapport d'essai mais une chaîne de preuves : au-delà de 0,1 % (m/m) ou non, obligation d'information remplie, SCIP déposé. Ce guide détaille les quatre obligations fermes de REACH, les substances les plus souvent détectées dans les pièces métalliques, le PVC souple, le caoutchouc foncé, les tissus teints et les enductions fluorées avec leur source réglementaire, le calcul du seuil par article et non par vêtement, l'auteur et le contenu du dépôt SCIP, les six documents à détenir, la réduction du risque par substitution et la liste à intégrer dans une demande de prix.",
        sum_es="Cuando un comprador de la UE pregunta si los accesorios contienen SVHC, la respuesta no es un informe de ensayo sino una cadena de pruebas: ¿más del 0,1 % (p/p)?, ¿se cumplió el deber de información?, ¿se presentó SCIP? Esta guía detalla las cuatro obligaciones firmes de REACH, las sustancias que más aparecen en piezas metálicas, PVC flexible, caucho oscuro, tejidos teñidos y recubrimientos fluorados con su fuente normativa, por qué el 0,1 % se calcula por artículo y no por prenda, quién presenta SCIP y con qué contenido, los seis documentos que debe tener el proveedor, la reducción de riesgo por sustitución y la lista para incluir en una solicitud de precio.",
    ),
    dict(
        slug="braille-tactile-label-guide.html",
        body="blog/_body_braille.html",
        title_zh="服装标签的盲文与触觉标识指南：无障碍设计怎么做 | TAGE",
        title_en="Braille and Tactile Labels on Garment Tags: An Accessibility Guide | TAGE",
        title_ja="衣料タグの点字・触覚表示ガイド：アクセシブルなラベル設計 | TAGE",
        title_ko="의류 태그의 점자·촉각 표시 가이드: 접근성 라벨 설계 | TAGE",
        title_fr="Étiquettes en braille et repères tactiles sur les vêtements : guide | TAGE",
        title_es="Etiquetas en braille y marcas táctiles en prendas: guía práctica | TAGE",
        desc_zh="服装标签上的盲文与触觉标识怎么做：点字规范与工艺门槛、凸点织造与压凸怎么选、洗后仍可辨认的验收条件、字号与对比度要求，以及吊牌与包装上的触觉设计要点，附打样与采购口径。来自东莞泰阁包装。",
        desc_en="Braille and tactile labels on garment tags: dot standards, woven vs embossed processes, wash durability, contrast and the design checks brands should run.",
        desc_ja="衣料タグの点字・触覚表示ガイド。点字の規範、織り凸点とエンボスの比較、洗濯後の耐久性、文字コントラストと設計チェック、タグ・包装の触覚設計、サンプルと発注の基準を整理。東莞泰閣包装。",
        desc_ko="의류 태그의 점자·촉각 표시 가이드. 점자 규범, 직조 볼록점과 엠보싱 비교, 세탁 후 내구성, 대비와 설계 점검, 행택·포장의 촉각 설계, 샘플과 발주 기준을 정리했습니다. 둥관 TAGE 패키징.",
        desc_fr="Braille et repères tactiles sur les étiquettes de vêtements : normes des points, tissage ou gaufrage, tenue au lavage, contraste et critères d'échantillonnage.",
        desc_es="Braille y marcas táctiles en etiquetas de prendas: normas de puntos, tejido o relieve, resistencia al lavado, contraste y criterios de muestreo y compra.",
        crumb_zh="触觉标签指南",
        crumb_en="Tactile Labels",
        crumb_ja="触覚ラベルガイド",
        crumb_ko="촉각 라벨 가이드",
        crumb_fr="Étiquettes tactiles",
        crumb_es="Etiquetas táctiles",
        h1_zh="服装标签的盲文与触觉标识指南：无障碍设计怎么做",
        h1_en="Braille and Tactile Labels on Garment Tags: An Accessibility Guide",
        h1_ja="衣料タグの点字・触覚表示ガイド：アクセシブルなラベル設計",
        h1_ko="의류 태그의 점자·촉각 표시 가이드: 접근성 라벨 설계",
        h1_fr="Étiquettes en braille et repères tactiles sur les vêtements : guide pratique",
        h1_es="Etiquetas en braille y marcas táctiles en prendas: guía práctica",
        tag_zh="标签设计",
        tag_en="Label Design",
        tag_ja="ラベル設計",
        tag_ko="라벨 설계",
        tag_fr="Design d'étiquettes",
        tag_es="Diseño de etiquetas",
        sum_zh="视力障碍的消费者同样要读到洗涤说明、尺码与成分。本文讲清服装标签上的盲文与触觉标识怎么做：先把法规与自愿的边界划清楚——欧盟《无障碍法案》管的是电商等信息服务，服装标签上的盲文目前是品牌自发的包容性设计，强制盲文只在药品包装；再对比标准盲文、触觉符号与可访问内容三个层次，比较织造凸点、纸卡压凸、厚膜丝印与贴附式四种工艺的耐久与手感，说明洗水标上的凸点怎么守住洗后可辨认，附吊牌与包装的触觉设计手法、设计端可访问性检查与打样采购口径。",
        sum_en="Consumers with a vision impairment need the care instructions, size and fibre content just as much. This guide covers braille and tactile marking on garment tags, starting with the legal boundary: the European Accessibility Act governs e-commerce and other information services, while braille on clothing labels is voluntary inclusive design today — mandatory braille sits on medicinal packaging. It then compares the three levels (standard braille, tactile symbols, accessible content), four processes (woven dots, paper embossing, thick-film UV, applied patches) for durability and feel, how to keep a tactile mark legible on a care label after washing, tactile design on hang tags and packaging, accessibility checks at the design stage, and sampling and sourcing criteria.",
        sum_ja="視覚に障害のある消費者も洗濯表示・サイズ・組成を必要とします。本記事は衣料タグの点字と触覚表示の作り方を扱います。まず法規と自主の境界を整理し、EU アクセシビリティ法が対象とするのは電子商取引などの情報サービスで、衣料ラベルの点字は現状ブランド側の自主的なインクルーシブデザイン、強制される点字は医薬品包装であることを示します。続いて標準点字・触覚記号・アクセシブルな内容の3層、織り凸点・紙カードのエンボス・厚膜 UV・貼付式の4加工の耐久と手触り、洗濯後も識別できる洗濯表示の作り方、タグと包装の触覚設計、設計段階の確認項目、サンプルと発注の基準をまとめます。",
        sum_ko="시각 장애 소비자도 세탁 지시, 사이즈, 조성 정보를 필요로 합니다. 이 글은 의류 태그에 점자와 촉각 표시를 넣는 방법을 다룹니다. 먼저 법규와 자발의 경계를 정리해 EU 접근성법이 규율하는 대상은 전자상거래 등 정보 서비스이고, 의류 라벨의 점자는 현재 브랜드 자발적 포용 설계이며 강제 점자는 의약품 포장에 있다는 점을 밝힙니다. 이어서 표준 점자·촉각 기호·접근 가능한 콘텐츠의 세 층, 직조 볼록점·종이 엠보싱·후막 UV·부착식 네 공정의 내구성과 촉감, 세탁 후에도 식별되는 세탁 라벨 만들기, 행택과 포장의 촉각 설계, 설계 단계 점검 항목, 샘플과 발주 기준을 정리합니다.",
        sum_fr="Les consommateurs malvoyants ont tout autant besoin des consignes d'entretien, de la taille et de la composition. Ce guide traite du braille et du marquage tactile sur les étiquettes de vêtements, en commençant par la frontière juridique : la loi européenne sur l'accessibilité encadre le commerce en ligne et les services d'information, tandis que le braille sur les étiquettes de vêtements relève aujourd'hui d'un design inclusif volontaire — le braille obligatoire concerne l'emballage des médicaments. Il compare ensuite les trois niveaux (braille standard, symboles tactiles, contenu accessible), quatre procédés (points tissés, gaufrage papier, sérigraphie UV épaisse, patchs rapportés) pour la durabilité et le toucher, la tenue d'une marque tactile après lavage, le design tactile des étiquettes pendantes et emballages, les contrôles d'accessibilité et les critères d'échantillonnage.",
        sum_es="Los consumidores con discapacidad visual necesitan igualmente las instrucciones de cuidado, la talla y la composición. Esta guía trata el braille y el marcado táctil en etiquetas de prendas, empezando por la frontera legal: la Ley Europea de Accesibilidad regula el comercio electrónico y otros servicios de información, mientras que el braille en etiquetas de ropa es hoy diseño inclusivo voluntario; el braille obligatorio está en el envase de medicamentos. Después compara los tres niveles (braille estándar, símbolos táctiles, contenido accesible), cuatro procesos (puntos tejidos, relieve en papel, serigrafía UV gruesa, parches aplicados) en durabilidad y tacto, cómo mantener la marca táctil legible tras el lavado, el diseño táctil de colgantes y embalajes, las comprobaciones de accesibilidad en diseño y los criterios de muestreo y compra.",
    ),
]
