#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-09-30 晚上（20:00）每日更新：2 篇新文章元数据（六语：zh-Hant 根 / en / ja / ko / fr / es）

选题（主题池 30 选题与历次扩展选题均已上线，本次沿「包装袋卡头（吊卡）」与
「包装袋防窒息警示语合规」两个方向扩展；已核对 blog/、en|ja|ko|fr|es/blog/ 与 sitemap.xml 无重复）：
- garment-bag-header-card-guide.html      服装包装袋卡头定制指南：尺寸、纸张与印刷工艺
- poly-bag-suffocation-warning-guide.html 包装袋防窒息警示语：法规要求、标准文案与印刷位置
"""

ARTICLES = [
    dict(
        slug="garment-bag-header-card-guide.html",
        body="blog/_body_headercard.html",
        title_zh="服装包装袋卡头定制指南：尺寸、纸张与印刷工艺 | TAGE",
        title_en="Poly Bag Header Card Guide: Sizes, Paper Stock and Printing | TAGE",
        title_ja="ポリ袋ヘッダーカードのカスタムガイド：寸法・紙・印刷 | TAGE",
        title_ko="폴리백 헤더 카드 가이드: 치수, 용지, 인쇄 | TAGE",
        title_fr="Carte d'en-tête pour sac poly : dimensions, papier et impression | TAGE",
        title_es="Tarjeta cabecera para bolsa: medidas, papel e impresión | TAGE",
        desc_zh="服装包装袋卡头怎么定尺寸、选纸张、配印刷？本文讲清卡头与吊牌的区别，给出常见尺寸与袋宽对应表、纸张克重与覆膜选择、烫金与环保油墨取舍、打孔固定方式与装箱配合，附询价六项。来自东莞泰阁包装。",
        desc_en="Poly bag header card guide: sizing a card against bag width, 300–400 gsm board and lamination choices, foil stamping and eco inks, punching and fixing.",
        desc_ja="ポリ袋ヘッダーカードのカスタムガイド。券（ハンガータグ）との違い、サイズと袋幅の対応表、300〜400gの紙とラミネートの選び方、箔押しと環境対応インキの判断、穴あけと固定方法、梱包との噛み合わせ、見積り時の6項目をまとめました。東莞泰閣包装。",
        desc_ko="폴리백 헤더 카드 맞춤 가이드. 행택과의 차이, 크기와 봉투 폭 대응표, 300~400g 용지와 라미네이팅 선택, 금박과 친환경 잉크의 판단, 타공과 고정 방식, 포장 상자와의 맞물림, 견적용 6항목을 정리했습니다. 둥관 TAGE 패키징.",
        desc_fr="Carte d'en-tête pour sac poly : correspondance entre dimensions et largeur de sac, carton 300 à 400 g, pelliculage, dorure et encres écologiques, perçage et mise en carton.",
        desc_es="Tarjeta cabecera para bolsa: correspondencia entre medidas y ancho de bolsa, cartulina de 300 a 400 g, laminado, foil y tintas ecológicas, perforado y embalaje.",
        crumb_zh="包装袋卡头",
        crumb_en="Header Cards",
        crumb_ja="ヘッダーカード",
        crumb_ko="헤더 카드",
        crumb_fr="Cartes d'en-tête",
        crumb_es="Tarjetas cabecera",
        h1_zh="服装包装袋卡头定制指南：尺寸、纸张与印刷工艺",
        h1_en="Poly Bag Header Card Guide: Sizes, Paper Stock and Printing",
        h1_ja="ポリ袋ヘッダーカードのカスタムガイド：寸法・紙・印刷",
        h1_ko="폴리백 헤더 카드 가이드: 치수, 용지, 인쇄",
        h1_fr="Carte d'en-tête pour sac poly : dimensions, papier et impression",
        h1_es="Tarjeta cabecera para bolsa de embalaje: medidas, papel e impresión",
        tag_zh="包装工艺", tag_en="Packaging", tag_ja="包装", tag_ko="포장",
        tag_fr="Emballage", tag_es="Embalaje",
        sum_zh="卡头是袋装产品在货架上的「第一张脸」：正面印品牌与规格，背面放尺码、条码或售后信息。它和吊牌、不干胶贴标解决的是不同场景，选错载体往往白花钱。本文给出卡头宽度与折后高度对袋宽的常见对应表，讲清白卡纸、单双铜、牛皮纸、黑卡与灰底白板各自的取舍与覆膜影响；印刷上区分胶印与数码、专色与四色、烫金压凹的适用边界；固定方式比较热封、订书钉、背胶条与袋底托板；最后给出袋宽公差、袋口增厚、防潮防卷曲与装箱方向四条配合要点，以及询价时必须交代的六项信息。",
        sum_en="A header card is the first face a bagged product shows on a shelf: brand and specification on the front, size, barcode or after-sales detail on the back. It is not a hang tag and not a sticker, and choosing the wrong carrier quietly wastes budget. This guide gives a working table of card width and folded height against bag width, sets out the trade-offs between coated white board, art paper, kraft, black board and grey-backed stock with the effect of lamination, separates offset from digital and spot from four-colour with the limits of foil and embossing, compares heat sealing, staples, adhesive strips and base boards, and closes with four fit points — bag width tolerance, added thickness at the seal, moisture and curl, carton orientation — plus the six items to send with your enquiry.",
        sum_ja="ヘッダーカードは袋商品の「最初の顔」です。表面にブランドと仕様、裏面にサイズ・バーコード・アフター情報を載せます。ハンガータグやステッカーとは役割が異なり、媒体選びを誤るとコストが無駄になります。本記事はカード幅・折り返し後の高さと袋幅の対応表、白板紙・コート紙・クラフト紙・黒卡紙・灰裏白板紙の使い分けとラミネートの影響、オフセットとデジタル、特色と4色、箔押し・型押しの適否、ヒートシール・ステープル・粘着テープ・底板の比較、そして袋幅公差・袋口の厚み増加・防湿と反り・梱包の向きという4つの噛み合わせ要点と、見積り時に伝えるべき6項目をまとめます。",
        sum_ko="헤더 카드는 봉투 제품이 매대에서 보여주는 첫 얼굴입니다. 앞면에 브랜드와 사양, 뒷면에 사이즈·바코드·애프터 정보를 넣습니다. 행택이나 스티커와 역할이 다르고, 매체를 잘못 고르면 비용만 낭비됩니다. 이 글은 카드 폭과 접은 뒤 높이를 봉투 폭에 맞춘 대응표, 백판지·아트지·크라프트지·블랙 카드·회색 심지 백판지의 선택과 라미네이팅 영향, 옵셋과 디지털, 별색과 4색, 금박·엠보싱의 적용 범위, 열봉합·스테이플·점착 테이프·바닥 받침 비교, 그리고 봉투 폭 공차·입구 두께 증가·방습과 휨·포장 방향이라는 네 가지 맞물림 요점과 견적 시 알려야 할 6항목을 정리합니다.",
        sum_fr="La carte d'en-tête est le premier visage d'un produit en sachet sur un linéaire : marque et spécifications au recto, taille, code-barres ou information après-vente au verso. Ce n'est ni une étiquette suspendue ni un autocollant, et se tromper de support gaspille du budget. Ce guide donne un tableau de correspondance largeur de carte et hauteur pliée face à la largeur du sac, détaille les compromis entre carton blanc couché, couché, kraft, carton noir et dos gris avec l'effet du pelliculage, sépare offset et numérique, Pantone et quadri, avec les limites de la dorure et du gaufrage, compare thermoscellage, agrafes, bandes adhésives et supports de fond, et termine par quatre points d'ajustement — tolérance de largeur, épaisseur ajoutée à la soudure, humidité et gondolement, sens de mise en carton — et six informations à joindre à votre demande.",
        sum_es="La tarjeta cabecera es la primera cara de un producto en bolsa en el lineal: marca y especificaciones en el anverso, talla, código de barras o información posventa en el reverso. No es una etiqueta colgante ni un adhesivo, y elegir mal el soporte desperdicia presupuesto. Esta guía ofrece una tabla de correspondencia entre ancho de tarjeta y altura plegada frente al ancho de bolsa, explica los compromisos entre cartulina blanca estucada, estucado, kraft, cartón negro y dorso gris con el efecto del laminado, separa offset y digital, color directo y cuatricromía con los límites del foil y el relieve, compara termosellado, grapas, tiras adhesivas y cartón de base, y cierra con cuatro puntos de ajuste —tolerancia de ancho, grosor añadido en el sellado, humedad y alabeo, sentido en la caja— y seis datos para la consulta.",
    ),
    dict(
        slug="poly-bag-suffocation-warning-guide.html",
        body="blog/_body_suffocation.html",
        title_zh="包装袋防窒息警示语：法规要求、标准文案与印刷位置 | TAGE",
        title_en="Poly Bag Suffocation Warning: Legal Text, Placement and Readability | TAGE",
        title_ja="ポリ袋の窒息注意表示：法規要件・標準文案・印刷位置 | TAGE",
        title_ko="폴리백 질식 경고: 법규 요건, 표준 문구, 인쇄 위치 | TAGE",
        title_fr="Avertissement d'étouffement sur les sacs poly : exigences, formulation et emplacement | TAGE",
        title_es="Aviso de asfixia en bolsas: requisitos, redacción estándar y ubicación | TAGE",
        desc_zh="包装袋防窒息警示语漏印、字号过小或自行改写，都可能让整批货被判不合规。本文讲清标准英文文案、适用范围判断、印刷位置与字号要求、多语言市场并列方式、袋面分区排版，以及七个常见错误与打孔袋等替代方案。来自东莞泰阁包装。",
        desc_en="Poly bag suffocation warning guide: standard wording, how to judge scope, placement and type size, multilingual markets, bag-face zoning and common mistakes.",
        desc_ja="ポリ袋の窒息注意表示ガイド。標準英文文案、適用範囲の判断、印刷位置と文字サイズ、多言語市場での併記、袋面のゾーニング、よくある7つの誤りと穴あき袋などの代替案をまとめました。東莞泰閣包装。",
        desc_ko="폴리백 질식 경고 가이드. 표준 영문 문구, 적용 범위 판단, 인쇄 위치와 글자 크기, 다국어 시장 병기 방식, 봉투 면 구역 설계, 흔한 실수 7가지와 타공 봉투 같은 대안을 정리했습니다. 둥관 TAGE 패키징.",
        desc_fr="Avertissement d'étouffement sur sacs poly : formulation standard, périmètre d'application, emplacement et corps de texte, marchés multilingues, zonage de la face et erreurs courantes.",
        desc_es="Aviso de asfixia en bolsas: redacción estándar, alcance de aplicación, ubicación y cuerpo de texto, mercados multilingües, zonificación de la cara y errores frecuentes.",
        crumb_zh="防窒息警示语",
        crumb_en="Suffocation Warnings",
        crumb_ja="窒息注意表示",
        crumb_ko="질식 경고",
        crumb_fr="Avertissements d'étouffement",
        crumb_es="Avisos de asfixia",
        h1_zh="服装包装袋防窒息警示语：法规要求、标准文案与印刷位置",
        h1_en="Poly Bag Suffocation Warning: Legal Text, Placement and Readability",
        h1_ja="ポリ袋の窒息注意表示：法規要件・標準文案・印刷位置",
        h1_ko="폴리백 질식 경고: 법규 요건, 표준 문구, 인쇄 위치",
        h1_fr="Avertissement d'étouffement sur les sacs poly : exigences, formulation et emplacement",
        h1_es="Aviso de asfixia en bolsas de embalaje: requisitos, redacción estándar y ubicación",
        tag_zh="包装合规", tag_en="Packaging Compliance", tag_ja="包装コンプライアンス", tag_ko="포장 규정",
        tag_fr="Conformité emballage", tag_es="Cumplimiento de envases",
        sum_zh="防窒息警示语只有几毫米高，却是塑料袋包装里抽查率最高的项目之一：漏印、字号过小、自行改写的文案，或临时贴上的贴纸在运输后翘边，都可能让整批货被判不合规。本文说明这条警示语的监管逻辑（美国对儿童用品配套塑料袋有明确标识要求，欧盟通过通用产品安全法规约束可预见风险），给出应当逐字引用的标准英文文案，讲清如何判断适用范围、印在袋面什么位置、字号与对比度怎么把握、为什么直印优于贴标，以及多语市场的并列方式与袋面三区排版法。最后列出七个常见错误，以及打孔袋、加厚袋膜、卡头承载警示语三条替代路线。",
        sum_en="A suffocation warning is only a few millimetres tall, yet it is one of the most frequently inspected items in poly bag packaging: a missing line, text too small, wording someone rewrote, or a sticker that lifts in transit can all push a shipment into non-compliance. This guide explains the regulatory logic behind the warning — explicit labelling rules for plastic bags supplied with children's articles in the United States, and general product safety legislation against foreseeable risk in the EU — quotes the standard English wording to reproduce word for word, shows how to judge whether your bag is in scope, where on the bag face to print, how to handle type size and contrast, why printing beats stickering, and how to set multilingual blocks and zone the bag face. It closes with seven common mistakes and three alternatives: perforated bags, heavier film, or carrying the warning on the header card.",
        sum_ja="窒息注意表示は数ミリの高さしかありませんが、ポリ袋包装で最も頻繁にチェックされる項目のひとつです。記載漏れ、小さすぎる文字、独自に書き換えた文言、輸送後に浮く仮貼りシールは、いずれも荷口を不適合に追い込みます。本記事はこの表示の規制の考え方（米国は子ども向け商品に付属するポリ袋に表示義務、EUは一般製品安全法規で予見可能なリスクを規制）、逐字で引用すべき標準英文文案、適用範囲の判断、袋面のどの位置に印刷するか、文字サイズとコントラストの扱い、印刷がシールより優れる理由、多言語の併記と袋面の三区分レイアウトを解説します。最後に7つのよくある誤りと、穴あき袋・厚手フィルム・ヘッダーカードに表示するという3つの代替案を示します。",
        sum_ko="질식 경고 문구는 몇 밀리미터에 불과하지만 폴리백 포장에서 가장 자주 검사되는 항목 중 하나입니다. 누락, 너무 작은 글자, 임의로 고친 문구, 운송 후 들떠 떨어지는 임시 스티커는 모두 화물을 부적합으로 몰아갑니다. 이 글은 이 경고의 규제 논리(미국은 아동용 제품에 딸린 폴리백에 표시 의무, EU는 일반 제품 안전 법규로 예견 가능한 위험을 규율), 그대로 인용해야 할 표준 영문 문구, 적용 범위 판단, 봉투 면 어디에 인쇄할지, 글자 크기와 대비 관리, 인쇄가 스티커보다 나은 이유, 다국어 병기와 봉투 면 3구역 배치법을 설명합니다. 마지막으로 흔한 실수 7가지와 타공 봉투·두꺼운 필름·헤더 카드에 표기하는 세 가지 대안을 제시합니다.",
        sum_fr="Un avertissement d'étouffement ne mesure que quelques millimètres, et pourtant c'est l'un des points les plus contrôlés en emballage poly : mention absente, texte trop petit, formulation réécrite ou autocollant qui se soulève en transport suffisent à rendre un lot non conforme. Ce guide explique la logique réglementaire — étiquetage explicite des sacs plastiques accompagnant des articles pour enfants aux États-Unis, législation générale sur la sécurité des produits contre les risques prévisibles dans l'UE — cite la formulation anglaise standard à reprendre mot pour mot, montre comment déterminer si votre sac est concerné, où imprimer sur la face, comment gérer corps et contraste, pourquoi l'impression vaut mieux qu'un autocollant, et comment gérer les blocs multilingues et le zonage de la face. Il termine par sept erreurs courantes et trois alternatives : sac perforé, film plus épais, ou avertissement porté par la carte d'en-tête.",
        sum_es="Un aviso de asfixia mide apenas unos milímetros, y sin embargo es uno de los puntos más inspeccionados en el embalaje de polietileno: una mención ausente, un texto demasiado pequeño, una redacción reescrita o una pegatina que se levanta en el transporte bastan para declarar un lote no conforme. Esta guía explica la lógica normativa —etiquetado explícito de las bolsas plásticas que acompañan artículos infantiles en Estados Unidos y legislación general de seguridad de productos frente a riesgos previsibles en la UE—, cita la redacción inglesa estándar que debe reproducirse palabra por palabra, muestra cómo determinar si tu bolsa entra en el alcance, dónde imprimir en la cara, cómo gestionar cuerpo y contraste, por qué imprimir gana a pegar, y cómo tratar los bloques multilingües y la zonificación de la cara. Cierra con siete errores frecuentes y tres alternativas: bolsa perforada, film más grueso o aviso alojado en la tarjeta cabecera.",
    ),
]
