#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-09-26 晚间批次文章元数据（六语）。"""

ARTICLES = [
    dict(
        slug="trim-tooling-ownership-guide.html",
        body="blog/_body_tooling.html",
        title_zh="辅料刀模、印版与版辊归属指南：版费、保管与换厂转移 | TAGE",
        title_en="Trim Tooling Ownership Guide: Dies, Plates and Plate Fees | TAGE",
        title_ja="副資材の型・版の所有権ガイド：版代・保管・工場変更時の移管 | TAGE",
        title_ko="부자재 금형·인쇄판 소유권 가이드: 판 비용·보관·공장 이전 | TAGE",
        title_fr="Propriété des outillages d'accessoires : découpes, clichés et frais | TAGE",
        title_es="Propiedad de los utillajes de accesorios: troqueles y clichés | TAGE",
        desc_zh="辅料刀模、烫金版与版辊的归属和版费怎么算？本文讲清各类版与模的复用性、版费的三种收法（一次性／满量返还／摊销进单价）、版权归谁、工厂保存几年、换供应商时哪些能带走，以及下单前确认清单。来自东莞泰阁包装。",
        desc_en="Trim tooling ownership and plate fees: how dies, foil stamps and print cylinders are charged, who owns them, storage life, and what moves to a new supplier.",
        desc_ja="副資材の型・版の所有権ガイド：タグの抜き型、箔押し版、織りラベルのジャカード版、ポリ袋のシリンダーの種類と再利用性、版代の3つの請求方式、顧客負担時の所有権、保管年限、工場変更時の移管と電子データ、発注前8項目。",
        desc_ko="부자재 금형·인쇄판 소유권 가이드: 행택 타발 금형, 박판, 직조 라벨 자카드 판, 포장백 실린더의 종류와 재사용성, 판 비용 청구 방식 세 가지, 고객 부담 시 소유권, 보관 연한, 공장 이전 시 이관, 발주 전 8가지 점검.",
        desc_fr="Propriété et frais de gravure des outillages : formes de découpe, clichés de dorure et cylindres, conservation et transfert vers un nouveau fournisseur.",
        desc_es="Propiedad y coste de plancha de los utillajes: troqueles, clichés de estampado y cilindros, formas de facturación, conservación y traslado al nuevo proveedor.",
        crumb_zh="版与模归属",
        crumb_en="Tooling Ownership",
        crumb_ja="型・版の所有権",
        crumb_ko="금형·판 소유권",
        crumb_fr="Outillages",
        crumb_es="Utillajes",
        h1_zh="辅料刀模、印版与版辊归属指南：版费怎么收、归谁、换厂能不能带走",
        h1_en="Trim Tooling Ownership: Dies, Plates, Fees and Transfers",
        h1_ja="副資材の型・版の所有権：版代・帰属・工場変更時の移管",
        h1_ko="부자재 금형·판 소유권: 판 비용·귀속·공장 이전",
        h1_fr="Propriété des outillages d'accessoires : frais, détention et transfert",
        h1_es="Propiedad de los utillajes: costes, titularidad y traslado",
        tag_zh="采购指南", tag_en="Sourcing", tag_ja="調達ガイド", tag_ko="조달 가이드",
        tag_fr="Guide d'achat", tag_es="Guía de compra",
        sum_zh="版费不止是「多少钱」：吊牌刀模、烫金版、织唛提花版与胶袋版辊的复用性差别很大，版费的收法有一次性、满量返还与摊销进单价三种，归属、保管年限与换厂时能否带走更决定长期成本。本文给出三种收法对比表、保管与提版流程，以及下单前八项确认清单。",
        sum_en="A plate fee is not just an amount: reusability differs by trim, fees are charged one-off, refunded at volume or amortised, and ownership, storage life and transferability shape your long-term cost. Includes comparison tables, a release process and an eight-point checklist.",
        sum_ja="版代は金額だけでは決まりません。型・版の再利用性は品目で異なり、請求方式は一括・数量達成返金・単価按分の3通り。所有権、保管年限、工場変更時の移管可否が長期コストを左右します。比較表、引き渡し手順、発注前8項目のチェックリスト付き。",
        sum_ko="판 비용은 금액만의 문제가 아닙니다. 금형 재사용성은 품목마다 다르고, 청구 방식은 일괄·수량 환급·단가 분산 세 가지이며, 소유권·보관 연한·이전 가능성이 장기 비용을 좌우합니다. 비교표, 인수 절차, 발주 전 8가지 점검 목록을 제공합니다.",
        sum_fr="Les frais de gravure ne se résument pas à un montant : la réutilisabilité varie selon l'accessoire, la facturation est unique, remboursée au volume ou amortie, et la propriété, la conservation et la transférabilité pèsent sur le coût à long terme.",
        sum_es="El coste de plancha no es solo un importe: la reutilización varía por accesorio, la facturación es única, devuelta por volumen o amortizada, y la propiedad, la conservación y la transferibilidad marcan el coste a largo plazo.",
    ),
    dict(
        slug="trim-limit-sample-inspection-guide.html",
        body="blog/_body_limitsample.html",
        title_zh="辅料外观验收的界限样品指南：缺陷判定口径怎么定 | TAGE",
        title_en="Limit Samples for Trim Inspection: Setting Visual Defect Standards | TAGE",
        title_ja="副資材の限界見本ガイド：外観判定基準の決め方 | TAGE",
        title_ko="부자재 한계 견본 가이드: 외관 판정 기준 정하는 법 | TAGE",
        title_fr="Échantillons limites pour le contrôle des accessoires | TAGE",
        title_es="Muestras límite en la inspección de accesorios | TAGE",
        desc_zh="辅料验收总在争「这算不算缺陷」？界限样品把可接受的最差一件做成实物标准，比文字有效得多。本文讲清黄金样、界限样与不可接受样的分工，四类辅料的高频争议缺陷，现场制作五步法，与 AQL 抽检的判定闭环，以及保存更新与争议处理。来自东莞泰阁包装。",
        desc_en="Limit samples for trim inspection: turning the worst acceptable piece into a visual standard for labels, tags and bags, with a five-step build and AQL grading.",
        desc_ja="限界見本ガイド：黄金見本・限界見本・不可見本の役割、織りラベル・タグ・洗濯表示・包装袋の紛争になりやすい欠点、現場での作り方5ステップ、AQLとの組み合わせ、保管と更新の考え方。",
        desc_ko="한계 견본 가이드: 골든 샘플·한계 견본·불합격 견본의 역할, 직조 라벨·행택·세탁 표시·포장백의 분쟁 잦은 결점, 현장 제작 5단계, AQL 샘플링과의 결합, 보관과 갱신 기준.",
        desc_fr="Échantillons limites : transformer la pire pièce acceptable en référence visuelle, rôles des trois types, création en cinq étapes et articulation avec l'AQL.",
        desc_es="Muestras límite: convertir la peor pieza aceptable en referencia visual, funciones de los tres tipos, creación en cinco pasos, uso con el AQL y conservación.",
        crumb_zh="验收界限样品",
        crumb_en="Limit Samples",
        crumb_ja="限界見本",
        crumb_ko="한계 견본",
        crumb_fr="Échantillons limites",
        crumb_es="Muestras límite",
        h1_zh="辅料外观验收的界限样品指南：缺陷判定口径怎么定",
        h1_en="Limit Samples for Trim Inspection: How to Set Visual Defect Standards",
        h1_ja="副資材の限界見本：外観判定基準の決め方",
        h1_ko="부자재 한계 견본: 외관 판정 기준 정하는 법",
        h1_fr="Échantillons limites pour le contrôle des accessoires",
        h1_es="Muestras límite para la inspección de accesorios",
        tag_zh="质检标准", tag_en="Quality", tag_ja="品質基準", tag_ko="품질 기준",
        tag_fr="Qualité", tag_es="Calidad",
        sum_zh="界限样品是把「可接受的最差一件」做成实物标准：验收时比它差就拒收、比它好就放行。本文讲清黄金样、界限样与不可接受样的分工，四类辅料的高频争议缺陷，现场制作五步法，与 AQL 2.5／4.0 分级配合的判定闭环，以及老化复核与争议处理口径。",
        sum_en="A limit sample turns the worst acceptable piece into a physical standard: anything worse is rejected. Covers golden, limit and reject samples, debated defects in four trim families, a five-step build and how it pairs with AQL grading.",
        sum_ja="限界見本は「許容できる最悪の1点」を実物基準にします。黄金見本・限界見本・不可見本の役割、4品目の紛争欠点、現場での5ステップ、AQL等級との組み合わせ、経年時の見直しと紛争対応を解説します。",
        sum_ko="한계 견본은 '허용 가능한 최악 1점'을 실물 기준으로 만듭니다. 골든·한계·불합격 견본의 역할, 네 품목의 분쟁 결점, 현장 5단계 제작, AQL 등급과의 결합, 노화 재검토와 분쟁 대응을 다룹니다.",
        sum_fr="L'échantillon limite transforme la pire pièce acceptable en référence physique. Rôles des trois types, défauts débattus pour quatre familles, création en cinq étapes, articulation avec l'AQL, révision et litiges.",
        sum_es="La muestra límite convierte la peor pieza aceptable en referencia física. Funciones de los tres tipos, defectos discutidos en cuatro familias, creación en cinco pasos, combinación con el AQL, revisión y disputas.",
    ),
]
