#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-09-30 下午（14:00）每日更新：2 篇新文章元数据（六语：zh-Hant 根 / en / ja / ko / fr / es）

选题（主题池 30 选题与历次扩展选题均已上线，本次沿「织唛织造密度与清晰度」与
「品牌侧辅料开发日历」两个方向扩展；已核对 blog/、en|ja|ko|fr|es/blog/ 与 sitemap.xml 无重复）：
- woven-label-density-guide.html      织唛密度与清晰度指南：纬密、最小字高与细节还原
- garment-trims-development-calendar.html  服装辅料开发日历：从设计定稿到下线的下单节奏
"""

ARTICLES = [
    dict(
        slug="woven-label-density-guide.html",
        body="blog/_body_density.html",
        title_zh="织唛密度与清晰度指南：纬密、最小字高与细节还原 | TAGE",
        title_en="Woven Label Density Guide: Weft Density, Small Text and Fine Detail | TAGE",
        title_ja="織りラベルの密度ガイド：緯密度・最小文字サイズ・細部の再現性 | TAGE",
        title_ko="직조 라벨 밀도 가이드: 위사 밀도, 최소 글자 크기, 세부 표현 | TAGE",
        title_fr="Densité des labels tissés : trame, petits textes et détails fins | TAGE",
        title_es="Densidad de las etiquetas tejidas: trama, textos pequeños y detalle fino | TAGE",
        desc_zh="织唛发虚、小字糊成一团，多数不是机器不行，而是密度与文件没配对。本指南讲清经密与纬密的区别、常见密度区间、最小可读字高与线宽、密度对柔软度与成本的影响，以及矢量文件与负空间的硬性要求，附可直接写进询价邮件的规格六项。来自东莞泰阁包装。",
        desc_en="Woven label density explained: warp versus weft density, density ranges by use, minimum readable text height and line width, plus softness and cost trade-offs.",
        desc_ja="織りラベルの密度ガイド。経密度と緯密度の違い、用途別の密度目安、読める最小文字高さと線幅、密度が柔らかさとコストに与える影響、ベクター入稿と余白の必須条件、見積りメールにそのまま使える仕様6項目をまとめました。東莞泰閣包装。",
        desc_ko="직조 라벨 밀도 가이드. 경사 밀도와 위사 밀도의 차이, 용도별 밀도 범위, 읽을 수 있는 최소 글자 높이와 선 굵기, 밀도가 부드러움과 원가에 미치는 영향, 벡터 원고와 여백 조건, 견적 메일에 바로 쓸 수 있는 사양 6항목을 정리했습니다. 둥관 TAGE 패키징.",
        desc_fr="Densité des labels tissés : chaîne et trame, plages de densité par usage, hauteur de texte et largeur de trait minimales, arbitrage souplesse et coût, fiche de spécifications en six points.",
        desc_es="Densidad de las etiquetas tejidas: urdimbre y trama, rangos de densidad por uso, altura mínima de texto y grosor de línea, equilibrio entre suavidad y coste y ficha de seis puntos.",
        crumb_zh="织唛密度与清晰度",
        crumb_en="Woven Label Density",
        crumb_ja="織りラベルの密度",
        crumb_ko="직조 라벨 밀도",
        crumb_fr="Densité des labels tissés",
        crumb_es="Densidad de etiquetas tejidas",
        h1_zh="织唛密度与清晰度指南：纬密、最小字高与细节还原",
        h1_en="Woven Label Density and Clarity: Weft Density, Minimum Text Height and Fine Detail",
        h1_ja="織りラベルの密度と明瞭度ガイド：緯密度・最小文字高・細部の再現",
        h1_ko="직조 라벨 밀도와 선명도 가이드: 위사 밀도, 최소 글자 높이, 세부 재현",
        h1_fr="Densité et netteté des labels tissés : trame, hauteur de texte minimale et détails fins",
        h1_es="Densidad y nitidez de las etiquetas tejidas: trama, altura mínima de texto y detalle fino",
        tag_zh="织唛工艺", tag_en="Woven Labels", tag_ja="織りラベル", tag_ko="직조 라벨",
        tag_fr="Labels tissés", tag_es="Etiquetas tejidas",
        sum_zh="「同样的文件，别人家织得清楚，我们家发虚」——这类问题十有八九不是设备，而是密度与文件没配对。本文把经密与纬密分开讲，给出主唛、袖标、贴身位置与婴童款的常见密度区间，说清最小可读字高（约 1.5–2 mm）与最细线宽（约 0.15–0.2 mm）这些能把预期写在合同前的数字，再讲密度如何同时抬高清晰度与成本、什么时候改用「减少颜色、加粗笔画、放大字号」更划算，最后给出矢量文件四条硬性要求与询价规格六项。",
        sum_en="Same artwork, crisp on one label and muddy on another — almost always a density and file mismatch, not the machine. This guide separates warp from weft density, gives common density ranges for neck labels, sleeve labels, next-to-skin and babywear, sets out the numbers worth writing into a spec (minimum readable text around 1.5–2 mm, finest line about 0.15–0.2 mm), shows how density raises clarity and cost together, explains when fewer colours and bolder strokes beat a denser weave, and closes with four hard artwork rules and six spec lines for your RFQ.",
        sum_ja="同じ入稿データなのに片方はくっきり、片方はぼやける——原因は設備ではなく密度とデータの不整合であることがほとんどです。本記事は経密度と緯密度を分けて解説し、メインラベル・袖ラベル・肌に接する位置・ベビー向けの密度目安、仕様書に書くべき数値（読める最小文字高は約1.5〜2mm、最小線幅は約0.15〜0.2mm）、密度が明瞭度とコストを同時に押し上げる仕組み、色数を減らし線を太くする方が得なケース、そしてベクター入稿の必須4条件と見積り用の仕様6項目をまとめます。",
        sum_ko="같은 원고인데 어떤 라벨은 선명하고 어떤 라벨은 뭉개진다면 장비가 아니라 밀도와 원고가 맞지 않은 것입니다. 이 글은 경사 밀도와 위사 밀도를 구분해 설명하고, 메인 라벨·소매 라벨·피부 접촉 부위·유아복의 밀도 범위, 사양서에 넣어야 할 수치(읽을 수 있는 최소 글자 높이 약 1.5~2mm, 최소 선 굵기 약 0.15~0.2mm), 밀도가 선명도와 원가를 함께 올리는 구조, 색 수를 줄이고 획을 굵게 하는 편이 유리한 경우, 벡터 원고 4가지 조건과 견적용 사양 6항목을 정리합니다.",
        sum_fr="Même fichier, net sur un label et brouillé sur un autre : presque toujours un problème de densité et de fichier, pas de machine. Ce guide sépare chaîne et trame, donne les plages de densité usuelles pour label de col, label de manche, zones à même la peau et layette, fixe les chiffres à inscrire au cahier des charges (hauteur de texte lisible d'environ 1,5–2 mm, trait le plus fin autour de 0,15–0,2 mm), montre comment la densité augmente à la fois netteté et coût, explique quand réduire les couleurs et épaissir les traits est plus rentable, et termine par quatre règles de fichier et six lignes de spécification.",
        sum_es="El mismo archivo, nítido en una etiqueta y emborronado en otra: casi siempre es una desajuste de densidad y archivo, no la máquina. Esta guía separa urdimbre y trama, da rangos habituales para etiqueta de cuello, de manga, zonas en contacto con la piel y ropa de bebé, fija las cifras que conviene escribir en la ficha (texto legible a partir de unos 1,5–2 mm, línea más fina en torno a 0,15–0,2 mm), muestra cómo la densidad sube a la vez nitidez y coste, explica cuándo conviene reducir colores y engrosar trazos, y cierra con cuatro reglas de archivo y seis líneas de especificación.",
    ),
    dict(
        slug="garment-trims-development-calendar.html",
        body="blog/_body_calendar.html",
        title_zh="服装辅料开发日历：从设计定稿到下线的下单节奏 | TAGE",
        title_en="Trims Development Calendar: From Design Freeze to Shipment | TAGE",
        title_ja="副資材の開発カレンダー：デザイン確定から出荷までの発注リズム | TAGE",
        title_ko="부자재 개발 캘린더: 디자인 확정부터 출하까지의 발주 리듬 | TAGE",
        title_fr="Calendrier de développement des accessoires : du design figé à l'expédition | TAGE",
        title_es="Calendario de desarrollo de accesorios: del diseño cerrado al embarque | TAGE",
        desc_zh="辅料晚定两天，成衣可能晚两周。这份开发日历把设计定稿、面料到位、产前样确认三个节点与上市倒排表串在一起，讲清打样与确认要留的提前量、滚动预测怎么共享，以及换季改版、春节、付款与清关这五个最容易踩的时间陷阱。来自东莞泰阁包装。",
        desc_en="A trims development calendar: the three freeze points, an eight-week countdown to launch, real sampling and approval lead times and five timing traps.",
        desc_ja="副資材の開発カレンダー。三つの中間確定点、上市までの逆算表、試作と承認に必要なリードタイム、繁忙期の行列を避けるローリング予測の共有方法、そして季節企画・春節・支払い・通関という五つの時間の落とし穴を解説します。東莞泰閣包装。",
        desc_ko="부자재 개발 캘린더. 세 가지 확정 시점, 출시 역산표, 샘플과 승인에 필요한 리드타임, 성수기 대기열을 피하는 롤링 예측 공유 방법, 시즌 개편·춘절·결제·통관이라는 다섯 가지 시간 함정을 정리했습니다. 둥관 TAGE 패키징.",
        desc_fr="Calendrier de développement des accessoires : trois points de gel, compte à rebours de huit semaines avant lancement, délais de prototype et d'approbation, cinq pièges de calendrier.",
        desc_es="Calendario de desarrollo de accesorios: tres puntos de congelación, cuenta atrás de ocho semanas, plazos de muestra y aprobación, previsión móvil y cinco trampas de calendario.",
        crumb_zh="辅料开发日历",
        crumb_en="Trims Development Calendar",
        crumb_ja="副資材の開発カレンダー",
        crumb_ko="부자재 개발 캘린더",
        crumb_fr="Calendrier de développement",
        crumb_es="Calendario de desarrollo",
        h1_zh="服装辅料开发日历：从设计定稿到下线的下单节奏",
        h1_en="Trims Development Calendar: Ordering Rhythm from Design Freeze to Shipment",
        h1_ja="副資材の開発カレンダー：デザイン確定から出荷までの発注リズム",
        h1_ko="부자재 개발 캘린더: 디자인 확정부터 출하까지의 발주 리듬",
        h1_fr="Calendrier de développement des accessoires : le rythme de commande du design figé à l'expédition",
        h1_es="Calendario de desarrollo de accesorios: el ritmo de pedido del diseño cerrado al embarque",
        tag_zh="采购节奏", tag_en="Sourcing", tag_ja="調達", tag_ko="조달",
        tag_fr="Approvisionnement", tag_es="Abastecimiento",
        sum_zh="辅料通常只占成衣成本的几个百分点，却常常是交期上最晚的一环：设计稿定了、面料到了，辅料还在打样。真正的风险不是「织唛要几天」，而是品牌侧日历里没有给辅料留位置。本文把设计定稿、面料到位、产前样确认三个节点与上市倒排表（T-12 到 T-0）串成一张可执行日历，给出打样与确认要留的提前量、把三个月滚动预测交给辅料厂的具体做法，并列出换季改版撞车、春节与国庆、旺季排产、付款与清关这五个最容易踩的时间陷阱。",
        sum_en="Trims are a few percent of garment cost but often the last item to fall into place: design signed off and fabric in house, with labels still at sampling. The real risk is not how long a woven label takes, but a brand calendar with no room reserved for trims. This guide links the three freeze points — design, fabric, pre-production sample — to an eight-week countdown to launch, sets out the lead times sampling and approval really need, shows how to hand a three-month rolling forecast to your trims supplier so peak season does not queue you, and lists five timing traps: clashing seasonal revisions, Chinese New Year and National Day, peak scheduling, payment and customs clearance.",
        sum_ja="副資材は衣料原価の数％にすぎませんが、納期で最後まで残る工程になりがちです。デザインが決まり生地も入ったのに、ラベルは試作中という状況です。本当のリスクは「織りラベルに何日かかるか」ではなく、ブランド側のカレンダーに副資材の枠がないことです。本記事はデザイン確定・生地入荷・産前サンプル承認の三つの確定点と上市までの逆算表（T-12〜T-0）をつなぎ、試作と承認に必要なリードタイム、3か月のローリング予測を副資材メーカーに渡す具体手順、そして季節改訂の衝突・春節と国慶節・繁忙期の生産枠・支払いと通関という五つの時間の落とし穴を整理します。",
        sum_ko="부자재는 의류 원가의 몇 퍼센트에 불과하지만 납기에서 가장 늦게 정리되는 항목이 되곤 합니다. 디자인과 원단은 확정됐는데 라벨은 아직 샘플 단계입니다. 진짜 위험은 직조 라벨에 며칠이 걸리는지가 아니라 브랜드 캘린더에 부자재 자리가 없다는 점입니다. 이 글은 디자인 확정, 원단 입고, 생산 전 샘플 승인이라는 세 시점과 출시 역산표(T-12~T-0)를 하나로 연결하고, 샘플과 승인에 실제로 필요한 리드타임, 3개월 롤링 예측을 부자재 공장에 전달하는 방법, 그리고 시즌 개편 충돌·춘절과 국경절·성수기 생산 배정·결제와 통관이라는 다섯 가지 시간 함정을 정리합니다.",
        sum_fr="Les accessoires représentent quelques pour cent du coût du vêtement, mais restent souvent le dernier maillon du délai : design signé, tissu reçu, labels encore en prototype. Le vrai risque n'est pas le nombre de jours d'un label tissé, c'est un calendrier de marque sans place réservée pour les accessoires. Ce guide relie les trois points de gel — design, tissu, échantillon de pré-production — à un compte à rebours de huit semaines avant lancement, fixe les délais réellement nécessaires au prototype et à l'approbation, explique comment confier une prévision glissante de trois mois à son fournisseur pour éviter la file de pointe, et liste cinq pièges : révisions de saison simultanées, Nouvel An chinois et Fête nationale, planification de pointe, paiement et dédouanement.",
        sum_es="Los accesorios son unos pocos puntos porcentuales del coste de la prenda, pero suelen ser el último eslabón del plazo: diseño firmado y tejido recibido, con las etiquetas aún en muestra. El riesgo real no es cuántos días tarda una etiqueta tejida, sino un calendario de marca sin sitio reservado para accesorios. Esta guía une los tres puntos de congelación —diseño, tejido, muestra de preproducción— con una cuenta atrás de ocho semanas, fija los plazos que realmente necesitan muestra y aprobación, explica cómo entregar una previsión móvil de tres meses al proveedor para no entrar en la cola de temporada alta, y enumera cinco trampas: revisiones de temporada simultáneas, Año Nuevo chino y Fiesta Nacional, planificación punta, pago y despacho de aduanas.",
    ),
]
