#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-09-26 下午批次（每日第 2 批）文章元数据：2 篇新文章 × 六语。
选题（主题池 30 个已全部上线，本次为运营/工艺扩展新选题，已核对 blog/ 文件、en|fr|es|ja|ko/blog 与 sitemap 无重复）：
- 服装辅料第三方检测送检指南：测试项目、样品量与报告解读
- 样衣间与打版房辅料常备清单：小批量出样不缺料
"""

ARTICLES = [
    dict(
        slug="trim-third-party-testing-guide.html",
        body="blog/_body_testlab.html",
        title_zh="服装辅料第三方检测送检指南：测试项目、样品量与报告解读 | TAGE",
        title_en="Third-Party Testing for Garment Trims: Tests, Samples &amp; Reports | TAGE",
        title_ja="衣料副資材の第三者試験ガイド：試験項目・サンプル量・報告書の読み方 | TAGE",
        title_ko="의류 부자재 제3자 시험 가이드: 시험 항목, 샘플 수량, 성적서 해석 | TAGE",
        title_fr="Essais par un laboratoire tiers des accessoires : tests, échantillons, rapports | TAGE",
        title_es="Ensayos de laboratorio externo para accesorios: pruebas, muestras e informes | TAGE",
        desc_zh="服装辅料第三方检测送检指南：从 RSL 与法规判断何时必须送检，讲清偶氮、甲醛、重金属、镍释放、邻苯等测试项目对应哪类辅料，送检流程与样品量，报告里最容易被忽略的四个细节，以及五种合法降本做法。来自东莞泰阁包装。",
        desc_en="Third-party testing for garment trims: when an RSL or regulation makes testing mandatory, which test fits which trim, sample quantities and how to read the report.",
        desc_ja="衣料副資材の第三者試験ガイド。RSLや法規で試験が必要になるケース、アゾ染料・ホルムアルデヒド・重金属・ニッケル溶出・フタル酸エステルと品目の対応、提出の流れとサンプル量、報告書で見落としやすい4点、コストを適正に下げる5つの方法を解説します。東莞泰閣包装。",
        desc_ko="의류 부자재 제3자 시험 가이드. RSL이나 법규로 시험이 필요한 경우, 아조 염료·포름알데히드·중금속·니켈 용출·프탈레이트와 품목 대응, 제출 절차와 샘플 수량, 성적서에서 놓치기 쉬운 네 가지, 비용을 낮추는 다섯 가지 방법을 정리했습니다. 둥관 TAGE 패키징.",
        desc_fr="Essais de laboratoire tiers pour les accessoires : quand un RSL ou une réglementation l'impose, quel essai pour quel accessoire, quantités d'échantillons et lecture du rapport.",
        desc_es="Ensayos de laboratorio externo para accesorios: cuándo lo exige un RSL o una norma, qué prueba corresponde a cada accesorio, cantidad de muestras y lectura del informe.",
        crumb_zh="第三方检测送检", crumb_en="Third-Party Testing", crumb_ja="第三者試験",
        crumb_ko="제3자 시험", crumb_fr="Essais tiers", crumb_es="Ensayos externos",
        h1_zh="服装辅料第三方检测送检指南：测试项目、样品量与报告解读",
        h1_en="Third-Party Testing for Garment Trims: Tests, Samples and Reports",
        h1_ja="衣料副資材の第三者試験ガイド：試験項目・サンプル量・報告書の読み方",
        h1_ko="의류 부자재 제3자 시험 가이드: 시험 항목, 샘플 수량, 성적서 해석",
        h1_fr="Essais par un laboratoire tiers des accessoires : tests, échantillons et rapports",
        h1_es="Ensayos de laboratorio externo para accesorios: pruebas, muestras e informes",
        tag_zh="合规指南", tag_en="Compliance", tag_ja="コンプライアンス", tag_ko="규정 준수",
        tag_fr="Conformité", tag_es="Cumplimiento",
        sum_zh="辅料送检最容易踩的坑不是费用，而是口径：测了不算、混测把单色超标平均掉、报告描述与大货不符。本文讲清什么时候必须送检、常见项目对应哪类辅料、流程与样品量、报告里四个容易被忽略的细节，以及五种合法降低检测成本的做法。",
        sum_en="The trap in trim testing is rarely the price — it is the scope: work done against the wrong standard, composite samples that average away a failing shade, reports that no longer describe the bulk. This guide covers when testing is mandatory, which test fits which trim, submission and sample quantities, four details easily missed in a report, and five legitimate ways to cut the cost.",
        sum_ja="副資材の試験でつまずくのは費用より範囲です。規格違いで測り直し、混合サンプルが1色の超過を平均化し、報告書の記載が量産と一致しない。本記事は、試験が必要なケース、品目ごとの対応項目、提出の流れとサンプル量、報告書で見落としやすい4点、コストを適正に下げる5つの方法を整理します。",
        sum_ko="부자재 시험에서 걸리는 것은 비용보다 범위입니다. 규격이 달라 재시험하고, 혼합 샘플이 한 색의 초과를 평균화하며, 성적서 기재가 양산과 일치하지 않습니다. 이 글은 시험이 필요한 경우, 품목별 대응 항목, 제출 절차와 샘플 수량, 성적서에서 놓치기 쉬운 네 가지, 비용을 적정하게 낮추는 다섯 가지 방법을 정리합니다.",
        sum_fr="Le piège des essais n'est pas le prix, c'est le périmètre : un essai fait selon une autre norme, un échantillon composite qui moyenne un coloris non conforme, un rapport qui ne décrit plus la production. Ce guide couvre l'obligation, l'essai adapté à chaque accessoire, les quantités, quatre détails souvent négligés et cinq façons de réduire le coût.",
        sum_es="La trampa de los ensayos no es el precio, sino el alcance: un ensayo hecho con otra norma, una muestra compuesta que diluye un color que falla, un informe que ya no describe la producción. Esta guía cubre la obligación, la prueba adecuada a cada accesorio, las cantidades, cuatro detalles que se pasan por alto y cinco formas de reducir el costo.",
    ),
    dict(
        slug="sample-room-trims-checklist.html",
        body="blog/_body_samproom.html",
        title_zh="样衣间与打版房辅料常备清单：小批量出样不缺料 | TAGE",
        title_en="Sample Room Trim Checklist: Sampling Without Waiting for Trims | TAGE",
        title_ja="サンプル室の副資材常備リスト：小ロット試作で欠品を出さない | TAGE",
        title_ko="샘플실 부자재 상비 목록: 소량 샘플 제작에 결품 없애기 | TAGE",
        title_fr="Liste d'accessoires pour atelier d'échantillons : échantillonner sans rupture | TAGE",
        title_es="Lista de accesorios para la sala de muestras: muestrear sin esperar | TAGE",
        desc_zh="样衣间与打版房辅料常备清单：三层备料结构（通用消耗件、可替代半成品、品牌专属件），品牌件缺货时的临时替代方案，库存水位与补货节奏，样衣标识与文件管理，以及与辅料供应商配合的五个做法。来自东莞泰阁包装。",
        desc_en="A sample room trim checklist: three tiers of standing stock, temporary substitutes when branded parts are late, stock levels and replenishment, plus sample records.",
        desc_ja="サンプル室・パタンナー室の副資材常備リスト。3層の在庫構成（汎用消耗品・代替可能な半製品・ブランド専用品）、ブランド品未着時の暫定代替、在庫水準と補充リズム、サンプルの識別と記録管理、サプライヤーとの連携5項目を解説します。東莞泰閣包装。",
        desc_ko="샘플실·패턴실 부자재 상비 목록. 3단계 재고 구조(범용 소모품, 대체 가능한 반제품, 브랜드 전용 부품), 브랜드 부품 미도착 시 임시 대체, 재고 수준과 보충 주기, 샘플 식별과 기록 관리, 공급업체 협업 다섯 가지를 정리했습니다. 둥관 TAGE 패키징.",
        desc_fr="Liste d'accessoires d'atelier : stock en trois niveaux, substituts temporaires quand les pièces de marque manquent, niveaux de réassort et archivage des échantillons.",
        desc_es="Lista de accesorios de sala de muestras: stock en tres niveles, sustitutos temporales si faltan piezas de marca, niveles de reposición y archivo de muestras.",
        crumb_zh="样衣间辅料清单", crumb_en="Sample Room Trims", crumb_ja="サンプル室の副資材",
        crumb_ko="샘플실 부자재", crumb_fr="Accessoires d'atelier", crumb_es="Accesorios de muestreo",
        h1_zh="样衣间与打版房辅料常备清单：小批量出样不缺料、不等货",
        h1_en="Sample Room Trim Checklist: Sampling Without Waiting for Trims",
        h1_ja="サンプル室・パタンナー室の副資材常備リスト：小ロット試作で欠品を出さない",
        h1_ko="샘플실·패턴실 부자재 상비 목록: 소량 샘플 제작에 결품 없애기",
        h1_fr="Liste d'accessoires pour atelier d'échantillons : échantillonner sans rupture",
        h1_es="Lista de accesorios para la sala de muestras: muestrear sin quedarse sin material",
        tag_zh="采购指南", tag_en="Sourcing Guide", tag_ja="調達ガイド", tag_ko="소싱 가이드",
        tag_fr="Guide d'achat", tag_es="Guía de compra",
        sum_zh="样衣间最怕的不是设计难做，而是缝到一半发现主唛没到、洗水标只剩两条。辅料件小价低，缺一件却卡住整件样衣。本文给出一份可直接照抄的常备清单：三层备料结构、品牌件缺货时的临时替代、库存水位与补货节奏、样衣标识与文件管理，以及和供应商配合的五个做法。",
        sum_en="The sample room's real problem is not design: it is discovering mid-garment that the neck label has not arrived and two care labels are left. Trims are small and cheap, yet one missing piece stops a sample. This is a checklist you can copy: three tiers of stock, temporary substitutes for late branded parts, replenishment rhythm, sample records and five ways to work with the supplier.",
        sum_ja="サンプル室で困るのはデザインではなく、縫い途中でメインラベル未着・洗濯表示ラベル残り2枚に気づくことです。副資材は小さく安価でも、1点欠けるとサンプルが止まります。そのまま使える常備リストとして、3層の在庫構成、ブランド品未着時の暫定代替、補充リズム、サンプル記録、サプライヤーとの連携5項目を提示します。",
        sum_ko="샘플실에서 문제가 되는 것은 디자인이 아니라, 봉제 도중 메인 라벨 미도착과 세탁 표시 라벨 두 장 남음을 알게 되는 순간입니다. 부자재는 작고 저렴하지만 한 가지가 없으면 샘플이 멈춥니다. 그대로 쓸 수 있는 상비 목록으로 3단계 재고 구조, 브랜드 부품 미도착 시 임시 대체, 보충 주기, 샘플 기록, 공급업체 협업 다섯 가지를 제시합니다.",
        sum_fr="Le problème de l'atelier n'est pas le design : c'est de découvrir à mi-parcours que le label de col n'est pas arrivé et qu'il reste deux étiquettes d'entretien. Les accessoires sont petits et bon marché, mais une pièce manquante arrête un prototype. Une liste à copier : stock en trois niveaux, substituts temporaires, rythme de réassort, archivage et cinq façons de travailler avec le fournisseur.",
        sum_es="El problema de la sala de muestras no es el diseño: es descubrir a mitad de la prenda que la etiqueta de cuello no llegó y quedan dos etiquetas de cuidado. Los accesorios son pequeños y baratos, pero una pieza que falta detiene la muestra. Una lista para copiar: stock en tres niveles, sustitutos temporales, ritmo de reposición, archivo de muestras y cinco formas de trabajar con el proveedor.",
    ),
]
