#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-09-27 晚间批次文章元数据（六语：zh-Hant 根 / en / ja / ko / fr / es）。

选题说明：任务主题池 30 个选题均已上线，本次为「供应商合规管理 + 价格与成本机制」方向扩展新选题。
已核对 blog/ 全量文件、en|ja|ko|fr|es/blog/ 与 sitemap.xml：
- 社会责任审核（Sedex/SMETA、BSCI、WRAP、SA8000）在现有正文中零覆盖（验厂文只讲质量与产能维度）
- 报价有效期、原材料价格波动、锁价、汇率条款在现有正文中零覆盖（报价对比文只讲口径对齐）
"""

ARTICLES = [
    dict(
        slug="trim-supplier-social-compliance-audit.html",
        body="blog/_body_socialaudit.html",
        title_zh="辅料供应商社会责任审核指南：Sedex、SMETA、BSCI 与验厂准备 | TAGE",
        title_en="Trim Supplier Social Compliance Audits: Sedex, SMETA, BSCI | TAGE",
        title_ja="副資材サプライヤーの社会的責任監査：Sedex・SMETA・BSCI と準備 | TAGE",
        title_ko="부자재 공급업체 사회적 책임 감사: Sedex·SMETA·BSCI와 준비 | TAGE",
        title_fr="Audit social fournisseur d'accessoires : Sedex, SMETA, BSCI | TAGE",
        title_es="Auditoría social de proveedores de accesorios: Sedex, SMETA, BSCI | TAGE",
        desc_zh="辅料供应商的社会责任审核怎么做：Sedex 与 SMETA、amfori BSCI、WRAP 的区别与有效期，工时工资、童工、消防与化学品等六个审核维度，文件与现场准备清单、费用与报告共享，以及采购方写进询价与合同的五条条款。来自东莞泰阁包装。",
        desc_en="Social compliance for trims suppliers: how Sedex, SMETA, BSCI, WRAP and SA8000 differ, what auditors check, how to prepare and what buyers should require.",
        desc_ja="副資材サプライヤーの社会的責任監査ガイド。Sedex と SMETA、amfori BSCI、WRAP、SA8000 の違いと有効期間、労働時間・賃金・児童労働・消防・化学物質など6つの観点、書類と現場の準備、報告共有、購買側が発注条件に書くべき条項を整理します。",
        desc_ko="부자재 공급업체 사회적 책임 감사 가이드. Sedex와 SMETA, amfori BSCI, WRAP, SA8000의 차이와 유효기간, 노동시간·임금·아동노동·소방·화학물질 등 여섯 관점, 서류와 현장 준비, 보고서 공유, 구매자가 발주 조건에 넣을 조항을 정리합니다.",
        desc_fr="Audit social fournisseur : différences entre Sedex, SMETA, BSCI, WRAP et SA8000, six dimensions contrôlées, préparation documentaire et sur site, partage des rapports et clauses à exiger.",
        desc_es="Auditoría social de proveedores: diferencias entre Sedex, SMETA, BSCI, WRAP y SA8000, seis dimensiones revisadas, preparación documental y en planta, compartición de informes y cláusulas exigibles.",
        crumb_zh="社会责任审核",
        crumb_en="Social Compliance",
        crumb_ja="社会的責任監査",
        crumb_ko="사회적 책임 감사",
        crumb_fr="Audit social",
        crumb_es="Auditoría social",
        h1_zh="辅料供应商社会责任审核指南：Sedex、SMETA、BSCI 与验厂准备要点",
        h1_en="Social Compliance Audits for Trim Suppliers: Sedex, SMETA, BSCI and How to Prepare",
        h1_ja="副資材サプライヤーの社会的責任監査ガイド：Sedex・SMETA・BSCIと準備の要点",
        h1_ko="부자재 공급업체 사회적 책임 감사 가이드: Sedex·SMETA·BSCI와 준비 요점",
        h1_fr="Audit social du fournisseur d'accessoires : Sedex, SMETA, BSCI et préparation",
        h1_es="Auditoría social del proveedor de accesorios: Sedex, SMETA, BSCI y preparación",
        tag_zh="合规审核", tag_en="Compliance", tag_ja="コンプライアンス", tag_ko="규정 준수",
        tag_fr="Conformité", tag_es="Cumplimiento",
        sum_zh="越来越多的欧洲品牌与零售商会把「有没有 Sedex 报告」写进第一封询价邮件。社会责任审核不看吊牌印得漂不漂亮，而看工时工资、童工防控、消防应急、化学品管理与可追溯体系的真实状态。本文区分社会责任审核、质量验厂与产品测试三条线，给出 Sedex 与 SMETA、amfori BSCI、WRAP、SA8000 的对照与有效期，列出文件与现场的准备清单、费用与报告共享的做法，并附五条可以直接写进询价邮件或采购合同的条款。",
        sum_en="More European brands open the first enquiry email with a single question: do you have a Sedex report? A social compliance audit reviews working hours and wages, child labour controls, fire safety, chemical management and traceability, not the look of a hang tag. This guide separates social audits from quality audits and product testing, compares Sedex with SMETA, amfori BSCI, WRAP and SA8000, lists what to prepare in documents and on the shop floor, explains cost and report sharing, and gives five clauses you can paste into an enquiry or a purchase contract.",
        sum_ja="欧州のブランドや小売が最初のメールで「Sedex の報告書はありますか」と尋ねる場面が増えています。社会的責任監査はタグの見栄えではなく、労働時間と賃金、児童労働の防止、消防、薬品管理、トレーサビリティの実態を見ます。本記事では社会的責任監査と品質監査・製品試験の違い、Sedex と SMETA、amfori BSCI、WRAP、SA8000 の比較と有効期間、書類と現場の準備項目、費用と報告共有、見積依頼や購買契約にそのまま使える5つの条項をまとめます。",
        sum_ko="유럽 브랜드와 유통사가 첫 문의 메일에서 'Sedex 보고서가 있습니까'를 묻는 경우가 늘고 있습니다. 사회적 책임 감사는 행택의 외형이 아니라 노동시간과 임금, 아동노동 방지, 소방, 화학물질 관리, 추적성의 실제 상태를 봅니다. 이 글에서는 사회적 책임 감사와 품질 심사·제품 시험의 차이, Sedex와 SMETA, amfori BSCI, WRAP, SA8000의 비교와 유효기간, 서류와 현장 준비 항목, 비용과 보고서 공유, 견적 요청이나 구매 계약에 바로 쓸 수 있는 다섯 가지 조항을 정리합니다.",
        sum_fr="De plus en plus de marques ouvrent leur première demande de prix par une question : avez-vous un rapport Sedex ? L'audit social examine heures et salaires, travail des enfants, incendie, produits chimiques et traçabilité, pas l'aspect d'une étiquette. Cet article distingue audit social, audit qualité et essais produit, compare Sedex-SMETA, amfori BSCI, WRAP et SA8000, liste la préparation documentaire et sur site, explique les coûts et le partage de rapports, et propose cinq clauses prêtes à l'emploi.",
        sum_es="Cada vez más marcas abren su primera solicitud de precio con una pregunta: ¿tienen informe Sedex? La auditoría social revisa horas y salarios, prevención del trabajo infantil, incendios, gestión de químicos y trazabilidad, no el aspecto del colgante. Este artículo separa auditoría social, auditoría de calidad y ensayos de producto, compara Sedex con SMETA, amfori BSCI, WRAP y SA8000, detalla la preparación documental y en planta, explica costes y compartición de informes y ofrece cinco cláusulas listas para usar.",
    ),
    dict(
        slug="trim-quotation-validity-guide.html",
        body="blog/_body_pricevalid.html",
        title_zh="辅料报价有效期与原材料价格波动：锁价、调价与分批交付 | TAGE",
        title_en="Trim Quotation Validity and Raw Material Price Moves | TAGE",
        title_ja="副資材見積りの有効期限と原材料価格の変動：価格固定・改定・分割納入 | TAGE",
        title_ko="부자재 견적 유효기간과 원자재 가격 변동: 가격 고정·조정·분할 납품 | TAGE",
        title_fr="Validité d'un devis d'accessoires et volatilité des matières premières | TAGE",
        title_es="Validez del presupuesto de accesorios y volatilidad de materias primas | TAGE",
        desc_zh="辅料报价为什么有有效期：吊牌纸张、织唛纱线、胶袋粒子与金属件的材料占比与波动来源，报价单必须写清的六项，固定价、浮动价与阶梯价的适用场景，锁价与备料、定金与汇率条款、分批交付与超期提货的谈法，附谈价前自查清单。来自东莞泰阁包装。",
        desc_en="Why trims quotes expire: material shares, six things a quotation must state, fixed vs floating vs tiered pricing, price locks, deposits and currency clauses.",
        desc_ja="副資材の見積りに有効期限がある理由を解説。タグ用紙、織りラベル糸、袋のペレット、金属部品の材料比率と変動要因、見積書に必須の6項目、固定価格・変動価格・階段価格の使い分け、価格固定と先行手配、着手金と為替条項、分割納入と引き取り遅延まで整理します。",
        desc_ko="부자재 견적에 유효기간이 있는 이유를 정리합니다. 행택용지, 직조 라벨 원사, 봉투 원료, 금속 부품의 재료 비중과 변동 요인, 견적서에 반드시 필요한 여섯 항목, 고정가·변동가·단계 가격의 선택, 가격 고정과 사전 자재 준비, 계약금과 환율 조항, 분할 납품과 인수 지연을 다룹니다.",
        desc_fr="Pourquoi un devis d'accessoires expire : part matière par catégorie, six mentions obligatoires, prix ferme, variable ou par paliers, blocage de prix, acompte, clause de change et livraisons fractionnées.",
        desc_es="Por qué caduca un presupuesto de accesorios: parte de material por categoría, seis datos obligatorios, precio fijo, variable o por tramos, bloqueo de precio, anticipo, cláusula de cambio y entregas parciales.",
        crumb_zh="报价有效期与价格波动",
        crumb_en="Quote Validity",
        crumb_ja="見積り有効期限",
        crumb_ko="견적 유효기간",
        crumb_fr="Validité des devis",
        crumb_es="Validez de la oferta",
        h1_zh="辅料报价有效期与原材料价格波动：锁价、调价与分批交付怎么谈",
        h1_en="Trim Quotation Validity and Raw Material Volatility: Locking Prices and Splitting Deliveries",
        h1_ja="副資材見積りの有効期限と原材料変動：価格固定・改定・分割納入の進め方",
        h1_ko="부자재 견적 유효기간과 원자재 변동: 가격 고정·조정·분할 납품 협상법",
        h1_fr="Validité du devis et volatilité des matières : blocage de prix, révisions et livraisons fractionnées",
        h1_es="Validez del presupuesto y volatilidad de materias: bloqueo de precio, revisiones y entregas parciales",
        tag_zh="价格与成本", tag_en="Pricing and Cost", tag_ja="価格とコスト", tag_ko="가격과 원가",
        tag_fr="Prix et coûts", tag_es="Precio y coste",
        sum_zh="辅料报价单上最容易起争执的往往不是单价，而是「有效期」那一行。吊牌用纸、织唛纱线、胶袋粒子与金属件都随国际原料行情浮动，报出去的价格随时可能失效。本文给出各品类的材料占比区间与波动来源，列出报价单必须写清的六项内容，比较固定价、浮动价与阶梯价各自适合的场景，说明锁价与备料、定金与汇率条款、分批交付与超期提货该怎么谈，最后附一张谈价前自查清单。",
        sum_en="The line that causes the most friction on a trims quote is rarely the unit price: it is the validity date. Paper, yarn, plastic granules and metal parts all follow commodity markets, so a quoted price can expire quickly. This article gives material-share ranges and volatility sources by category, lists the six things a quotation must state, compares fixed, floating and tiered pricing, and explains how to negotiate price locks, material stocking, deposits, currency clauses and split deliveries, closing with a self-check before negotiating.",
        sum_ja="副資材の見積書でもめやすいのは単価ではなく「有効期限」の一行です。タグ用紙、織りラベルの糸、袋のペレット、金属部品はいずれも国際相場で動くため、提示した価格はすぐに古くなります。本記事では品目別の材料比率と変動要因、見積書に必ず書くべき6項目、固定価格・変動価格・階段価格の使い分け、価格固定と先行手配、着手金と為替条項、分割納入と引き取り遅延の交渉、最後に交渉前のセルフチェックをまとめます。",
        sum_ko="부자재 견적서에서 다툼이 생기는 부분은 단가가 아니라 '유효기간' 한 줄입니다. 행택용지, 직조 라벨 원사, 봉투 원료, 금속 부품은 국제 시세를 따라 움직여 제시한 가격이 곧 만료됩니다. 이 글에서는 품목별 재료 비중과 변동 요인, 견적서에 반드시 써야 할 여섯 항목, 고정가·변동가·단계 가격의 비교, 가격 고정과 사전 자재 준비, 계약금과 환율 조항, 분할 납품과 인수 지연 협상법, 마지막으로 협상 전 자체 점검을 정리합니다.",
        sum_fr="Sur un devis d'accessoires, la ligne qui fâche n'est pas le prix unitaire mais la durée de validité. Papier, fil, granulés et pièces métalliques suivent les marchés mondiaux : un prix peut devenir caduc rapidement. Cet article donne les parts matière et les sources de volatilité par catégorie, les six mentions obligatoires d'un devis, la comparaison prix ferme, variable et par paliers, puis la négociation du blocage de prix, de l'approvisionnement, de l'acompte, de la clause de change et des livraisons fractionnées.",
        sum_es="En un presupuesto de accesorios la línea que más fricción crea no es el precio unitario, sino la validez. Papel, hilo, granza y piezas metálicas siguen los mercados internacionales, así que un precio puede caducar pronto. Este artículo ofrece rangos de parte de material y orígenes de volatilidad por categoría, los seis datos que un presupuesto debe indicar, la comparación entre precio fijo, variable y por tramos, y cómo negociar bloqueo de precio, acopio, anticipo, cláusula de cambio y entregas parciales.",
    ),
]
